"use client";

/* eslint-disable @next/next/no-img-element -- Existing local lesson artwork, no network dependency. */
import { useEffect, useState } from 'react';
import { ArrowRight, Moon, Sun, Sunrise, Utensils, Play } from 'lucide-react';
import type { GroundMeasurementVisual } from '@/data/assessments/revisions/groundMeasurementFiveForms';
import ReadAloudBtn from '@/components/ReadAloudBtn';
import { groundMeasurementVisualSpeech } from '@/data/assessments/revisions/groundMeasurementVisualSpeech';

const ink='#3b2a14';
const colours:Record<string,string>={Red:'#dc4545',Blue:'#287fb7',Green:'#16876b',Purple:'#8554b7',Orange:'#d97916'};
function ObjectPicture({name,x,y,size=65}:{name:string;x:number;y:number;size?:number}){
 const assets:Record<string,{file:string; width:number; height:number; bounds:string}>={
  Book:{file:'book',width:1536,height:1024,bounds:'348 86 906 840'},
  Apple:{file:'apple',width:1254,height:1254,bounds:'215 137 821 912'},
  Stone:{file:'rock',width:1254,height:1254,bounds:'158 244 938 798'},
  Ball:{file:'soccer-ball',width:1254,height:1254,bounds:'177 124 908 917'},
  Bag:{file:'backpack',width:1254,height:1254,bounds:'232 110 808 1025'},
 };
 const asset=assets[name];
 // Ignore transparent export padding so the object sits on the balance pan.
 if(asset)return <svg x={x-size/2} y={y-size} width={size} height={size} viewBox={asset.bounds} preserveAspectRatio="xMidYMax meet"><image href={`/images/measurelands/week2-3d/${asset.file}.png`} width={asset.width} height={asset.height}/></svg>;
 return <g transform={`translate(${x-size/2},${y-size}) scale(${size/70})`} stroke={ink} strokeWidth="2.5" strokeLinejoin="round">
  {name==='Stone'?<path d="M5 60L9 30 27 10 49 15 65 38 61 60Z" fill="#a3b2b9"/>:name==='Sponge'?<><rect x="4" y="20" width="62" height="40" rx="9" fill="#f5cf62"/>{[15,32,49].map(cx=><circle key={cx} cx={cx} cy="37" r="4" fill="#d0a83c" stroke="none"/>)}</>:name==='Tin'?<><path d="M12 15V59Q35 72 58 59V15" fill="#90bbc1"/><ellipse cx="35" cy="15" rx="23" ry="9" fill="#cfedef"/><path d="M12 32H58M12 49H58" stroke="#50828b"/></>:name==='Ball'?<><circle cx="35" cy="35" r="31" fill="#f5aa65"/><path d="M5 35H65M35 4Q10 35 35 66M35 4Q60 35 35 66" fill="none"/></>:name==='Cup'?<><path d="M53 20H61Q78 36 54 43" fill="none"/><path d="M8 15H55L50 58Q31 70 13 58Z" fill="#deb9ed"/></>:name==='Bag'?<><path d="M14 22H56L64 64H6Z" fill="#dfa76a"/><path d="M22 23V17Q35 -1 48 17V23" fill="none"/></>:<><path d="M6 23L35 8 64 23V59L35 69 6 59Z" fill={name==='Block'?'#e6aa64':'#c99d75'}/><path d="M6 23L35 35 64 23M35 35V69" fill="none"/></>}
 </g>;
}
export default function GroundMeasurementAssessmentVisual({visual:v}:{visual:GroundMeasurementVisual}){
 const values=v.values??[],paint=v.labels.map(l=>colours[l]??'#16876b');
 let content;
 if(v.task==='length'||v.task==='align')content=<svg viewBox="0 0 600 235" className="mx-auto w-full max-w-2xl" role="img" aria-label={v.description}>
  {v.task==='length'?<path d="M175 28V203" stroke="#ad8a52" strokeWidth="3" strokeDasharray="6 6"/>:null}
  {v.labels.map((label,i)=>{const x=v.task==='align'?175+i*75:175,y=55+i*95;return <g key={label}><text x="20" y={y+27} fontSize="25" fontWeight="700" fill={ink}>{label}</text>{v.objects?.[i]==='pencil'?<><path d={`M${x} ${y}H${x+values[i]-25}L${x+values[i]} ${y+20}L${x+values[i]-25} ${y+40}H${x}Z`} fill={paint[i]} stroke={ink} strokeWidth="2"/><path d={`M${x+values[i]-25} ${y}L${x+values[i]} ${y+20}L${x+values[i]-25} ${y+40}Z`} fill="#ecd1a3"/><path d={`M${x+values[i]-8} ${y+14}L${x+values[i]} ${y+20}L${x+values[i]-8} ${y+26}Z`} fill={ink}/></>:<><rect x={x} y={y} width={values[i]} height="40" rx="5" fill={paint[i]}/><path d={`M${x+6} ${y+10}H${x+values[i]-6}`} stroke="white" strokeOpacity=".35" strokeWidth="4"/></>}</g>})}
 </svg>;
 else if(v.task==='height')content=<svg viewBox="0 0 600 280" className="mx-auto w-full max-w-2xl" role="img" aria-label={v.description}><path d="M100 225H500" stroke="#ad8a52" strokeWidth="5"/>{v.labels.map((label,i)=><g key={label}><rect x={155+i*230} y={225-values[i]} width="80" height={values[i]} rx="4" fill={paint[i]}/><path d={`M${165+i*230} ${225-values[i]+10}V215`} stroke="white" strokeOpacity=".3" strokeWidth="7"/><text x={195+i*230} y="263" textAnchor="middle" fontSize="25" fontWeight="700" fill={ink}>{label}</text></g>)}</svg>;
 else if(v.task==='mass')content=<svg viewBox={v.scene==='size-trap'?"55 45 490 290":"0 0 600 340"} className="mx-auto w-full max-w-2xl" role="img" aria-label={v.description}><path d="M300 105L265 275H335Z" fill="#d4ab60" stroke="#8b642f" strokeWidth="3"/><rect x="235" y="275" width="130" height="16" rx="8" fill="#8b642f"/><line x1="150" y1={values[0]} x2="450" y2={values[1]} stroke="#8b642f" strokeWidth="9" strokeLinecap="round"/><circle cx="300" cy="100" r="9" fill="#ffdc86" stroke="#8b642f" strokeWidth="3"/>{v.labels.map((label,i)=>{const x=150+i*300,pan=values[i]+110;return <g key={label}><path d={`M${x-68} ${pan}L${x} ${values[i]}L${x+68} ${pan}`} fill="none" stroke="#a78043" strokeWidth="3"/><path d={`M${x-70} ${pan}Q${x} ${pan+42} ${x+70} ${pan}Z`} fill={i?'#c49ed8':'#6cbbb1'} stroke="#76592f" strokeWidth="3"/><ObjectPicture name={label} x={x} y={pan-4} size={v.scene==='size-trap'?(i===0?60:100):64}/><text x={x} y="325" textAnchor="middle" fontSize="25" fontWeight="700" fill={ink}>{v.scene==='size-trap'?`${i===0?'Small':'Large'} ${label.toLowerCase()}`:label}</text></g>})}</svg>;
 else if(v.task==='capacity')content=<div><p className="mb-4 text-center text-lg font-bold text-amber-950">Pour from {v.labels[v.source!]} until {v.labels[1-v.source!]} is full.</p><div className="grid items-center gap-3 sm:grid-cols-[1fr_auto_1fr]">{[false,true].map((after,index)=><div key={index} className="contents">{after?<ArrowRight className="mx-auto rotate-90 text-amber-700 sm:rotate-0" aria-hidden/>:null}<div className="rounded-2xl border border-amber-200 bg-white p-3"><p className="text-center text-lg font-black text-amber-950">{after?'After pouring':'At first'}</p><svg viewBox="0 0 280 235" className="mx-auto w-full max-w-sm" role="img" aria-label={after?`The receiving container is full. ${v.equal?'The first is empty.':'Water is left in the first container.'}`:'The first container is full. The receiving container is empty.'}>{v.labels.map((label,i)=>{const source=i===v.source,w=v.equal?80:source?96:64,x=70+i*140,fill=after?(source?(v.equal?0:32/90):1):(source?1:0);return <g key={label}><text x={x} y="32" textAnchor="middle" fontSize="23" fontWeight="700" fill={ink}>{label}</text>{fill>0?<rect x={x-w/2+3} y={167-104*fill} width={w-6} height={104*fill} fill="#73c5e8"/>:null}<path d={`M${x-w/2} 63V170H${x+w/2}V63`} fill="none" stroke={paint[i]} strokeWidth="5"/><path d={`M${x-w/2} 63H${x+w/2}`} stroke={paint[i]} strokeWidth="2" strokeDasharray="4 4"/><text x={x} y="211" textAnchor="middle" fontSize="19" fill={ink}>{fill===0?'Empty':fill===1?'Full':'Water left'}</text></g>})}</svg></div></div>)}</div></div>;
 else if(v.task==='duration')content=<DurationComparison key={v.labels.join('-')} visual={v}/>;
 else if(v.task==='daypart')content=<div className="mx-auto max-w-sm"><img src={`/images/measurelands/${v.art}`} alt={v.description} width="360" height="360" className="aspect-square w-full rounded-2xl object-contain"/></div>;
 else if(v.task==='weekday')content=<div><p className="mb-4 text-center text-lg font-bold text-amber-900">{v.context}</p><div className="flex items-center justify-center gap-3">{v.days!.map((day,i)=><div className="contents" key={i}>{i>0?<ArrowRight className="shrink-0 text-amber-700" aria-hidden/>:null}<div className="min-w-0 flex-1 overflow-hidden rounded-xl border-2 border-amber-300 bg-white text-center"><div className="h-5 bg-amber-300"/><p className="px-2 py-7 text-xl font-black text-amber-950 sm:text-3xl">{day}</p></div></div>)}</div></div>;
 else content=<div><p className="mb-4 text-center text-lg font-bold text-amber-900">{v.context}</p><div className="grid gap-3 sm:grid-cols-3">{[1,2,0].map(i=>{const Icon=v.objects?.[i]==='moon'?Moon:v.objects?.[i]==='sunrise'?Sunrise:v.objects?.[i]==='lunch'?Utensils:Sun;return <div key={i} className="flex items-center gap-3 rounded-xl border border-amber-200 bg-white p-4 sm:flex-col">{v.scene==='dayparts'?<img src={`/images/measurelands/timeofday-3d/${['morning','lunch','afternoon'][i]}.png`} alt="" width="140" height="140" className="h-28 w-28 rounded-xl object-contain"/>:<Icon size={48} className="shrink-0 text-amber-700"/>}<p className="text-center text-lg font-bold text-amber-950">{v.labels[i]}</p></div>})}</div><p className="mt-4 text-center text-base text-amber-900">Tap the answers below in order.</p></div>;
 return <section className="mb-5 rounded-2xl border-2 border-amber-200 bg-[#fffaf0] p-4 shadow-sm sm:p-6"><div className="mb-3 flex justify-end"><ReadAloudBtn text={groundMeasurementVisualSpeech(v)} label="Read diagram" size="md" /></div>{content}</section>;
}

function DurationComparison({visual:v}:{visual:GroundMeasurementVisual}){
 const [elapsed,setElapsed]=useState<number|null>(null);
 const [run,setRun]=useState(0);
 const longest=Math.max(...v.values!)*20;
 useEffect(()=>{if(run===0)return;let frame=0;const started=performance.now();const tick=()=>{const time=Math.min(longest,performance.now()-started);setElapsed(time);if(time<longest)frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[run,longest]);
 return <div><p className="mb-4 text-center text-lg font-bold text-amber-950">Both start together.</p>{v.labels.map((label,i)=>{const finished=elapsed===null||elapsed>=v.values![i]*20;const length=elapsed===null?v.values![i]:Math.min(v.values![i],elapsed/20);return <div key={label} className="mb-4 grid grid-cols-[128px_1fr] items-center gap-3"><div className="flex flex-col items-center gap-2"><img src={`/images/measurelands/${v.activityArts![i]}`} alt="" width="128" height="128" className="h-28 w-28 rounded-xl object-contain"/><span className="text-lg font-black text-amber-950">{label}</span></div><div className="border-l-4 border-amber-700 pl-1"><div className="flex h-12 items-center justify-end overflow-hidden rounded-r-xl px-1 text-sm font-bold text-white" style={{width:`${length/280*100}%`,background:i?'#865cb1':'#178773'}}>{finished?'Finished':''}</div></div></div>})}<p className="text-center text-sm text-amber-900">The strip stops growing when the activity finishes.</p><button type="button" onClick={()=>{setElapsed(0);setRun(n=>n+1);}} className="mx-auto mt-4 flex min-h-12 items-center gap-2 rounded-xl border-2 border-amber-700 bg-white px-4 py-2 font-bold text-amber-950"><Play size={20}/> Watch both activities</button></div>;
}
