import { Backpack, GlassWater, PaintBucket, Package, Ticket, Users, Wallet, Sparkles, Snowflake, Sun, Truck } from 'lucide-react';
import { FractionText } from '@/components/FractionText';
import type { ReactNode } from 'react';
import Year7ContextArt from './Year7ContextArt';

const money=(n:unknown)=>`$${Number(n).toFixed(2)}`;
function Card({label,value,note,icon}:{label:string;value:ReactNode;note?:string;icon?:ReactNode}){
 return <div className="min-w-0 rounded-xl border border-teal-900/15 bg-white p-4 shadow-sm sm:p-5"><div className="mb-3 flex items-center gap-2 text-sm font-bold text-teal-800">{icon}{label}</div><div className="text-3xl font-black tabular-nums text-slate-950">{value}</div>{note&&<p className="mt-2 text-sm font-semibold leading-relaxed text-slate-600">{note}</p>}</div>;
}
function Context({art,children}:{art:Parameters<typeof Year7ContextArt>[0]['kind'];children:ReactNode}){
 return <div className="flex flex-col items-center gap-4 sm:flex-row sm:items-center sm:gap-6"><Year7ContextArt kind={art}/><div className="w-full min-w-0 flex-1">{children}</div></div>;
}
function Expression({value}:{value:string}){
 const root=value.match(/^√(\d+)$/);
 return <div className="relative flex min-h-36 flex-wrap items-center justify-center gap-3 rounded-2xl border border-teal-200/80 bg-white px-5 py-7 text-4xl font-black tabular-nums text-slate-950 shadow-[0_5px_0_0_#ccfbf1] sm:gap-5 sm:text-5xl">
  {root?<span className="inline-flex items-end"><span className="text-6xl font-normal text-teal-700">√</span><span className="border-t-[3px] border-teal-700 px-2 pb-1 pt-2">{Number(root[1]).toLocaleString('en-AU')}</span></span>
   :value.split(' ').filter(Boolean).map((part,i)=>/^[+×÷−]$/.test(part)?<span key={i} className="text-3xl font-medium text-teal-600 sm:text-4xl">{part}</span>:<span key={i} className={/^\d+\/\d+$/.test(part)?'rounded-xl bg-teal-50 px-5 py-3':''}>{/^\d+\/\d+$/.test(part)?<FractionText value={part}/>:/^\d{5,}$/.test(part)?Number(part).toLocaleString('en-AU'):part}</span>)}
 </div>;
}
export default function NumberNexusYear7AssessmentVisual({visual:v}:{visual:Record<string,unknown>}){
 let content:ReactNode;
 switch(v.kind){
  case 'ordering':content=<div className="flex items-center justify-between gap-4 rounded-xl bg-white px-5 py-3 text-sm font-bold text-slate-600"><span className="flex items-center gap-2"><Snowflake className="text-sky-600"/>Colder</span><span className="h-px flex-1 bg-gradient-to-r from-sky-300 to-amber-300"/><span className="flex items-center gap-2">Warmer<Sun className="text-amber-500"/></span></div>;break;
  case 'factors':content=<div className="grid grid-cols-2 gap-5">{(v.values as number[]).map(n=><div key={n} className="rounded-2xl border border-teal-200 bg-white px-4 py-8 text-center text-5xl font-black text-slate-950 shadow-[0_5px_0_0_#ccfbf1]">{n}</div>)}</div>;break;
  case 'power':content=<div className="flex min-h-36 flex-wrap items-center justify-center gap-4 rounded-2xl border border-teal-200 bg-white px-5 py-7 text-3xl font-black tabular-nums text-slate-950 shadow-sm sm:text-4xl"><span>{Number(v.number).toLocaleString('en-AU')}</span><span className="font-medium text-teal-600">=</span><span>{String(v.digit)}</span><span className="font-medium text-teal-600">×</span><span>10<sup className="ml-1 rounded border-2 border-dashed border-teal-600 bg-teal-50 px-2 text-xl">?</sup></span></div>;break;
  case 'estimate':content=<Context art="fabric"><div className="grid gap-4 sm:grid-cols-2"><Card label="Fabric length" value={`${v.metres} m`} note="Round to the nearest whole metre."/><Card label="Price for ONE metre" value={money(v.price)} note="Round to the nearest whole dollar."/></div></Context>;break;
  case 'mixture':content=<Context art="drink"><div className="grid gap-4 sm:grid-cols-2"><Card label="Total drink to make" value={`${v.total} mL`} icon={<GlassWater size={20}/>}/><Card label="Concentrate : Water" value={String(v.ratio)} note="Use this mixing ratio."/></div></Context>;break;
  case 'packs':content=<div className="grid gap-4 sm:grid-cols-2">{(v.packs as Array<{label:string;kg:number;price:number}>).map(p=><div key={p.label} className="flex items-center gap-2 rounded-xl border border-teal-200 bg-white px-3 py-2 shadow-sm"><div className="hidden shrink-0 sm:block"><Year7ContextArt kind="pack"/></div><div className="py-3"><p className="mb-2 flex items-center gap-2 font-bold text-teal-800"><Package size={18}/>{p.label}</p><p className="text-3xl font-black text-slate-950">{p.kg} kg</p><p className="mt-2 text-lg font-bold text-slate-700">{money(p.price)} <span className="text-sm font-medium">per pack</span></p></div></div>)}</div>;break;
  case 'expression':content=<Expression value={String(v.expression)}/>;break;
  case 'square':content=<svg viewBox="0 0 520 235" role="img" aria-label={`Square with area ${v.area} square metres. Side lengths are unknown.`} className="mx-auto w-full max-w-lg"><rect x="174" y="29" width="188" height="188" fill="#115e59" opacity=".1"/><rect x="164" y="19" width="188" height="188" fill="#fff" stroke="#0f766e" strokeWidth="3"/><rect x="176" y="31" width="164" height="164" fill="#f0fdfa"/><path d="M164 37H182V19M334 19V37H352M164 189H182V207M334 207V189H352" stroke="#14b8a6" strokeWidth="2" fill="none"/><text x="258" y="94" textAnchor="middle" fontSize="16" fontWeight="bold" fill="#0f766e">SQUARE AREA</text><text x="258" y="135" textAnchor="middle" fontSize="32" fontWeight="bold" fill="#0f172a">{String(v.area)} m²</text></svg>;break;
  case 'number-line':content=<div className="rounded-2xl border border-teal-200 bg-white px-3 py-5 shadow-sm"><p className="mb-2 text-center text-sm font-semibold text-slate-600">Each unit is divided into 4 equal parts.</p><svg viewBox="0 0 720 140" role="img" aria-label="Number line from negative three to one, divided into quarters, with point P marked." className="w-full"><line x1="32" x2="688" y1="66" y2="66" stroke="#1e293b" strokeWidth="3"/>{Array.from({length:17},(_,i)=><g key={i}><line x1={32+i*41} x2={32+i*41} y1={i%4===0?52:58} y2={i%4===0?80:74} stroke="#334155" strokeWidth="2"/>{i%4===0&&<text x={32+i*41} y="115" textAnchor="middle" fontSize="21" fontWeight="bold" fill="#0f172a">{i/4-3}</text>}</g>)}<circle cx={32+(Number(v.marker)+3)*164} cy="66" r="15" fill="#ccfbf1"/><circle cx={32+(Number(v.marker)+3)*164} cy="66" r="9" fill="#0d9488" stroke="white" strokeWidth="3"/><text x={32+(Number(v.marker)+3)*164} y="35" textAnchor="middle" fontSize="20" fontWeight="bold" fill="#0f766e">P</text></svg></div>;break;
  case 'paint':content=<Context art="paint"><div className="grid gap-4 sm:grid-cols-2"><Card label="Paint needed" value={`${v.litres} L`} icon={<PaintBucket size={20}/>}/><Card label="One full tin" value={`${v.tin} L`} note="Buy whole tins. No paint is left over from another job."/></div></Context>;break;
  case 'ratio':content=<div className="grid gap-4 sm:grid-cols-2">{[['Blue',Number(v.blue),'bg-sky-500 border-sky-700'],['Orange',Number(v.orange),'bg-amber-400 border-amber-600']].map(([label,count,color])=><Card key={String(label)} label={`${label} counters`} value={<><div className="mb-4 flex flex-wrap gap-2" aria-hidden="true">{Array.from({length:Number(count)},(_,i)=><span key={i} className={`h-7 w-7 rounded-full border-2 shadow-[inset_0_2px_0_0_#ffffff70,0_2px_2px_0_#0f172a15] ${color}`}/>)}</div><span className="text-2xl">{count} <span className="text-base font-semibold text-slate-500">counters</span></span></>}/>)}</div>;break;
  case 'share':content=<Context art="wallet"><div className="grid gap-4 sm:grid-cols-2"><Card label="Total to share" value={money(v.total)} icon={<Wallet size={20}/>}/><Card label="Alex : Sam" value={String(v.ratio)} note="Share the whole amount in this ratio." icon={<Users size={20}/>}/></div></Context>;break;
  case 'delivery':content=<Context art="backpack"><div className="grid gap-3 md:grid-cols-3"><Card label="One backpack" value={money(v.price)} note="Original price" icon={<Backpack size={20}/>}/><Card label="Backpack discount" value={`${v.discount}% off`} note="Applies to the backpack only."/><Card label="Delivery" value={money(v.delivery)} note="Add once after the discount." icon={<Truck size={20}/>}/></div></Context>;break;
  case 'fundraiser':content=<Context art="tickets"><div className="grid gap-3 md:grid-cols-3"><Card label="Total event cost" value={money(v.cost)} note="All expenses included." icon={<Wallet size={20}/>}/><Card label="Tickets sold" value={String(v.tickets)} icon={<Ticket size={20}/>}/><Card label="Price for ONE ticket" value={money(v.price)} note="No other income."/></div></Context>;break;
  default:return null;
 }
 return <div className="overflow-hidden rounded-2xl border border-teal-200 bg-[#f0fdfa] text-slate-950 shadow-sm"><div className="flex items-center gap-2 border-b border-teal-200/70 bg-gradient-to-r from-teal-100 to-[#f0fdfa] px-5 py-3 text-xs font-bold uppercase tracking-widest text-teal-800"><Sparkles size={15} aria-hidden="true"/>{String(v.topic??'Number Nexus')}</div><div className="p-4 sm:p-6">{content}</div></div>;
}
