"use client";
import ReadAloudBtn from '@/components/ReadAloudBtn';
import Year4MeasurementAssessmentVisual from './Year4MeasurementAssessmentVisual';
import {MeasurelandsProtractor} from '@/components/measurelands/MeasurelandsProtractor';
import {MeasurelandsAngle} from '@/components/measurelands/MeasurelandsAngle';
import {DimensionedArea,areaSpeech,TravelScene,LibraryScene} from './Measurement5Scenes';
import {ArrowRight} from 'lucide-react';
import type {Measurement5Visual} from '@/data/assessments/revisions/year5MeasurementFiveForms';
export function measurement5Speech(v:Measurement5Visual){return [v.description,...v.labels??[],areaSpeech(v),...(v.task==='protractor'||v.task==='construct'?['Protractor scales run from zero to one hundred and eighty degrees in opposite directions.']:[])].join(' ');}
export default function Year5MeasurementAssessmentVisual({visual:v,value,onChange}:{visual:Measurement5Visual;value?:string|null;onChange?:(value:string)=>void}){
 if(v.base)return <Year4MeasurementAssessmentVisual visual={v.base}/>;
 const n=v.values;let content;
 if(v.task==='construct'){
  const current=value&&value!=='idk'?Number(value):0;
  const set=(deg:number)=>onChange?.(String(Math.max(0,Math.min(180,Math.round(deg)))));
  content=<div className="mx-auto max-w-2xl rounded-xl outline-none focus-visible:ring-4 focus-visible:ring-amber-400" tabIndex={0} role="slider" aria-label="Constructed angle. Arrow keys move the arm one degree." aria-valuemin={0} aria-valuemax={180} aria-valuenow={current} onKeyDown={event=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();set(current+(['ArrowRight','ArrowUp'].includes(event.key)?1:-1));}}}><MeasurelandsProtractor interactive currentDeg={current} onDeg={set} guidance="none" showInteractiveReading={false} size={640}/></div>;
 }else if(v.task==='protractor')content=<div className="flex justify-center"><MeasurelandsProtractor angle={n[0]} baselineSide={v.baseline} guidance="none" size={640}/></div>;
 else if(v.task==='estimate')content=<div role="img" aria-label="Two arms with a curved arc marking the opening." className="flex justify-center"><div aria-hidden="true"><MeasurelandsAngle turn={n[0]} size={350}/></div></div>;
 else if(v.task==='precision'&&v.art)content=<img src={`/images/measurelands/${v.art}`} alt={v.labels![0]} style={{height:230,width:'100%',objectFit:'contain'}}/>;
 else if(v.task==='precision'&&n[0]===4)content=<svg viewBox="0 0 340 150" style={{height:200,width:'100%'}} role="img" aria-label="A thin coin viewed from the side and above."><ellipse cx="170" cy="86" rx="100" ry="31" fill="#b78b3f" stroke="#735221" strokeWidth="3"/><ellipse cx="170" cy="75" rx="100" ry="31" fill="#efd28c" stroke="#735221" strokeWidth="3"/><ellipse cx="170" cy="75" rx="83" ry="22" fill="none" stroke="#b78b3f" strokeWidth="2"/></svg>;
 else if(v.task==='precision')content=<svg viewBox="0 0 400 130" className="mx-auto w-full max-w-sm" role="img" aria-label="A small metal screw."><defs><linearGradient id="y5-screw" x2="0" y2="1"><stop stopColor="#cdd4db"/><stop offset=".5" stopColor="#f4f6f7"/><stop offset="1" stopColor="#84939f"/></linearGradient></defs><g transform={`translate(${n[0]*8} 0) scale(${1-n[0]*.04} 1)`}><path d="M95 47H280L318 65L280 83H95Z" fill="url(#y5-screw)" stroke="#596974" strokeWidth="3"/>{Array.from({length:11},(_,i)=><path key={i} d={`M${105+i*16} 47l-12 36`} stroke="#697c89" strokeWidth="3"/>)}<rect x="70" y="29" width="35" height="72" rx="7" fill="url(#y5-screw)" stroke="#596974" strokeWidth="3"/><path d="M81 42V88" stroke="#596974" strokeWidth="6"/></g></svg>;
 else if(v.task==='rectangleArea'||v.task==='compositeArea')content=<div className="flex justify-center"><DimensionedArea values={n} cut={v.task==='compositeArea'}/></div>;
 else if(v.task==='combinedArea')content=<div style={{display:'flex',flexWrap:'wrap',justifyContent:'center',gap:20}}>{[0,2].map(i=><div key={i} style={{flex:'1 1 280px',maxWidth:460}}><p className="text-center font-bold text-amber-950">{v.labels![i/2]}</p><DimensionedArea values={n.slice(i,i+2)} label={v.labels![i/2]}/></div>)}</div>;
 else if(v.task==='mixed')content=<div className="flex flex-wrap justify-center gap-5">{v.labels!.map(label=><div key={label} className="flex min-w-56 flex-col items-center gap-4 rounded-2xl border border-amber-200 bg-white p-5"><img src={`/images/measurelands/${v.art}`} alt="" width={200} height={140} className="h-36 w-52 object-contain"/><p className="text-center text-2xl font-black text-amber-950">{label}</p></div>)}</div>;
 else if(v.task==='time')content=<div className="mx-auto flex max-w-md flex-col items-center gap-4 rounded-2xl border border-amber-300 bg-white p-7">{v.labels![0].startsWith('Library')?<LibraryScene/>:<TravelScene coach={v.labels![0].startsWith('Coach')}/>}<p className="text-lg font-bold text-amber-950">{v.labels![0]}</p><p className="rounded-xl bg-amber-50 px-6 py-4 text-4xl font-black tabular-nums text-amber-950">{v.labels![1]}</p></div>;
 else content=<div className="mx-auto max-w-2xl rounded-2xl border border-amber-300 bg-white p-6"><div className="flex justify-center"><TravelScene/></div><div className="flex flex-wrap items-center justify-center gap-5">{v.labels!.map((label,i)=><div key={label} className="flex items-center gap-5">{i?<ArrowRight aria-hidden="true" className="text-amber-700"/>:null}<p className="rounded-xl bg-amber-50 p-5 text-2xl font-black tabular-nums text-amber-950">{label}</p></div>)}</div></div>;
 return <div className="w-full rounded-2xl border-2 border-amber-300 bg-[#fffaf0] p-4 sm:p-6"><div className="mb-4 flex justify-end"><ReadAloudBtn text={measurement5Speech(v)} size="sm" label="Read diagram" className="!border-amber-600 !bg-[#fffaf0] !text-amber-900"/></div><p className="mb-5 text-center text-lg font-bold text-amber-950">{v.description}</p>{content}</div>;
}
