'use client';
import ChanceCompoundVisual from '@/components/chance-hollow/ChanceCompoundVisual';
import ChanceWeatherForecast from '@/components/chance-hollow/ChanceWeatherForecast';
import ChanceContextScene from '@/components/chance-hollow/ChanceContextScene';
import ChanceOutcomePicture from './ChanceOutcomePicture';
import {MathFormattedText} from '@/components/FractionText';
import {chEmpty,chSpeech,chOutcome,type CHItem,type CHResponse} from '@/data/assessments/revisions/level3ChanceHollowFiveForms';
import ChanceVisual from '@/components/chance-hollow/ChanceVisual';
import ReadAloudBtn from '@/components/ReadAloudBtn';
import styles from './StatisticaFiveForms.module.css';
import ch from './ChanceHollowFiveForms.module.css';
export default function ChanceHollowAssessmentCard({item:q,response:r,update,level}:{item:CHItem;response:CHResponse;update:(r:CHResponse)=>void;level:number}){
 const pictureResults=level===3&&(q.slot===11||q.slot===12),trials=q.mode==='experiment'?r.trials:q.trials;
 const trial=()=>{if(r.trials.length>=q.target!)return;const next=q.batchStages?.find(n=>n>r.trials.length)??r.trials.length+1,count=next-r.trials.length,compound=q.experiment==='coinPair'||q.experiment==='diceDifference',u=new Uint32Array(count*(compound?2:1));crypto.getRandomValues(u);const trials=[...r.trials,...Array.from({length:count},(_,i)=>compound?chOutcome(q,u[i*2]/4294967296,u[i*2+1]/4294967296):chOutcome(q,u[i]/4294967296))];update({...r,trials,values:[],skipped:false,snapshots:q.batchStages?[...(r.snapshots??[]),{total:next,counts:q.outcomes!.map(o=>trials.filter(t=>t===o).length)}]:undefined});};
 return <> <div className={styles.question}><h2 id='ch-question'><MathFormattedText text={q.prompt}/></h2><ReadAloudBtn text={[q.prompt,q.instruction].filter(Boolean).join('. ')} label='Read question' className={styles.voice}/></div>{q.instruction&&<p className={styles.instruction}>{q.instruction}</p>}
 <div className={styles.activity}><div className={styles.source}><div className={styles.panelHeader}><h3>{q.mode==='experiment'?'Try the experiment':q.rows||trials?'Experiment results':'Look at the evidence'}</h3><ReadAloudBtn text={chSpeech(q,r)} label='Read diagram' className={styles.voice}/></div>
 <p className={ch.caption}><MathFormattedText text={q.caption}/></p>
 {q.forecastPercent!==undefined?<ChanceWeatherForecast percent={q.forecastPercent}/>:q.scene&&<ChanceContextScene scene={q.scene} count={Number(q.caption.match(/^\d+/)?.[0])||undefined}/>}
 {(q.tree||q.venn)&&<ChanceCompoundVisual tree={q.tree} venn={q.venn}/>}
 {q.tiles&&<div className={ch.tiles} aria-label='Given outcomes or values'>{q.tiles.map((t,i)=><span key={i}><MathFormattedText text={t}/></span>)}</div>}
 {q.scale&&<svg viewBox='0 0 440 110' role='img' aria-label='Probability scale from 0 to 1 and 0 percent to 100 percent'><line x1='32' y1='45' x2='408' y2='45' stroke='currentColor' strokeWidth='3'/>{[0,.25,.5,.75,1].map((v,i)=><g key={v}><line x1={32+i*94} y1='36' x2={32+i*94} y2='54' stroke='currentColor'/><text x={32+i*94} y='26' textAnchor='middle' fontSize='16'>{v}</text><text x={32+i*94} y='77' textAnchor='middle' fontSize='16'>{v*100}%</text></g>)}</svg>}

 {q.apparatus&&<div className={`${ch.apparatus} ${q.batchStages?ch.simApparatus:''}`}><ChanceVisual visual={q.apparatus}/></div>}
 {q.displays&&<div className={ch.displays}>{q.displays.map(d=><div key={d.label}><h4>{d.label}</h4><ChanceVisual visual={d.apparatus}/><p>{d.caption}</p></div>)}</div>}
 {q.mode==='experiment'&&<div className={ch.experiment}><button className={styles.primary} disabled={r.trials.length===q.target} onClick={trial}>{q.batchStages?`Run to ${q.batchStages.find(n=>n>r.trials.length)??q.target} trials`:q.apparatus?.type==='die'?'Roll die':q.experiment==='coin'?'Toss coin':q.experiment==='twoCoins'?'Toss both coins':'Spin'}</button><span aria-live='polite'>{r.trials.length}/{q.target} trials{r.trials.length>0?` · Latest: ${r.trials.at(-1)}`:''}</span></div>}
 {q.batchStages&&r.snapshots&&(q.outcomes!.length>4?<table className={`${styles.frequencyTable} ${ch.simTable}`}><caption>Results as the trial count increases</caption><thead><tr><th scope='col'>Outcome</th>{r.snapshots.map(s=><th scope='col' key={s.total}>{s.total} trials</th>)}</tr></thead><tbody>{q.outcomes!.map((o,i)=><tr key={o}><th scope='row'>{o}</th>{r.snapshots!.map(s=><td key={s.total}>{s.counts[i]}<br/><small>{Math.round(s.counts[i]/s.total*10000)/100}%</small></td>)}</tr>)}</tbody></table>:<table className={`${styles.frequencyTable} ${ch.simTable}`}><caption>Results as the trial count increases</caption><thead><tr><th scope='col'>Trials</th>{q.outcomes!.map(o=><th scope='col' key={o}>{o}</th>)}</tr></thead><tbody>{r.snapshots.map(s=><tr key={s.total}><th scope='row'>{s.total}</th>{s.counts.map((n,i)=><td key={i}>{n}<br/><small>{Math.round(n/s.total*10000)/100}%</small></td>)}</tr>)}</tbody></table>)}
 {!q.batchStages&&trials&&trials.length>0&&<ol className={`${ch.trials} ${pictureResults?ch.pictureTrials:''}`} aria-label='Trial results'>{trials.map((t,i)=><li key={i}><small>{i+1}</small>{pictureResults&&<ChanceOutcomePicture outcome={t}/>}<strong>{t}</strong></li>)}</ol>}
 {q.matrix&&<div className={ch.matrix}><table className={styles.frequencyTable}><caption>Difference between the two dice</caption><thead><tr><th scope='col'>Die 1 ↓ / Die 2 →</th>{[1,2,3,4,5,6].map(n=><th scope='col' key={n}>{n}</th>)}</tr></thead><tbody>{q.matrix.map((row,i)=><tr key={i}><th scope='row'>{i+1}</th>{row.map((n,j)=><td key={j}>{n}</td>)}</tr>)}</tbody></table></div>}
 {q.pairTable&&<table className={styles.frequencyTable}><thead><tr><th scope='col'>First / Second</th>{q.pairTable.second.map(b=><th scope='col' key={b}>{b}</th>)}</tr></thead><tbody>{q.pairTable.first.map((a,i)=><tr key={a}><th scope='row'>{a}</th>{q.pairTable!.cells[i].map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table>}
 {q.rows&&(q.outcomes!.length>4?<table className={styles.frequencyTable}><thead><tr><th scope='col'>Outcome</th>{q.rows.map(row=><th scope='col' key={row.label}>{row.label}</th>)}</tr></thead><tbody>{q.outcomes!.map((o,i)=><tr key={o}><th scope='row'>{o}</th>{q.rows!.map(row=><td key={row.label}>{row.counts[i]}</td>)}</tr>)}</tbody></table>:<table className={styles.frequencyTable}><thead><tr><th scope='col'>{q.rowHeading??'Experiment'}</th>{q.outcomes!.map(o=><th scope='col' key={o}>{o}</th>)}</tr></thead><tbody>{q.rows.map(row=><tr key={row.label}><th scope='row'>{row.label}</th>{row.counts.map((n,i)=><td key={i}>{n}</td>)}</tr>)}</tbody></table>)}
 </div><div className={styles.answer}>
 {q.mode==='complete'?<><div className={styles.panelHeader}><h3>Complete the diagram</h3><ReadAloudBtn text={q.completion!.map(field=>`${field.label}. Choices: ${field.choices.join(', ')}`).join('. ')} label='Read choices' className={styles.voice}/></div><div className={styles.entries}>{q.completion!.map((field,i)=><label key={field.label}>{field.label}<select value={r.values[i]??''} onChange={e=>{const values=[...r.values];values[i]=e.target.value;update({...r,values,skipped:false});}}><option value=''>Choose…</option>{field.choices.map(value=><option key={value} value={value}>{value}</option>)}</select></label>)}</div></>:q.mode==='choice'?q.options.map((o,i)=><div className={styles.option} key={o}><button aria-pressed={!r.skipped&&r.choice===i} onClick={()=>update({...chEmpty(),choice:i})}><MathFormattedText text={o}/></button><ReadAloudBtn text={o} label='Read answer' className={styles.voice}/></div>):<><div className={styles.panelHeader}><h3>Your results table</h3><ReadAloudBtn text={`Record how many times each outcome appeared: ${q.outcomes!.join(', ')}. ${q.mode==='experiment'?'Complete all trials first.':''}`} label='Read table' className={styles.voice}/></div><table className={styles.frequencyTable}><thead><tr><th scope='col'>Outcome</th><th scope='col'>Number of times</th></tr></thead><tbody>{q.outcomes!.map((o,i)=><tr key={o}><th scope='row'><span className={pictureResults?ch.outcomeKey:undefined}>{pictureResults&&<ChanceOutcomePicture outcome={o}/>}<span>{o}</span></span></th><td><input className={ch.input} aria-label={`${o} count`} inputMode='numeric' value={r.values[i]??''} disabled={q.mode==='experiment'&&r.trials.length!==q.target} onChange={e=>{const values=[...r.values];values[i]=e.target.value.replace(/\D/g,'').slice(0,5);update({...r,values,skipped:false});}}/></td></tr>)}</tbody></table>{q.mode==='experiment'&&r.trials.length!==q.target&&<p>Complete all {q.target} trials to fill in your table.</p>}</>}
 </div></div></>;
}
