import type { Metadata } from "next";
import { Suspense } from "react";
import "./globals.css";
import { ErrorBoundary } from "@/components/ErrorBoundary";
import { GlobalTapFeedback } from "@/components/GlobalTapFeedback";
import { FullscreenToggle } from "@/components/FullscreenToggle";
import StudentScreenRecorder from "@/components/StudentScreenRecorder";
import DemoPreviewBanner from "@/components/demo/DemoPreviewBanner";
import GemRevealHost from "@/components/gems/GemRevealHost";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ErrorBoundary>
          <GlobalTapFeedback />
          <FullscreenToggle />
          <StudentScreenRecorder />
          <Suspense fallback={null}>
            <DemoPreviewBanner />
          </Suspense>
          {children}
          <GemRevealHost />
        </ErrorBoundary>
      </body>
    </html>
  );
}
