import type { Metadata } from "next";
import "./globals.css";
import { ErrorBoundary } from "@/components/ErrorBoundary";
import { GlobalTapFeedback } from "@/components/GlobalTapFeedback";
import { FullscreenToggle } from "@/components/FullscreenToggle";
import { Analytics } from "@vercel/analytics/next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ErrorBoundary>
          <GlobalTapFeedback />
          <FullscreenToggle />
          {children}
        </ErrorBoundary>
        <Analytics />
      </body>
    </html>
  );
}
