'use client';
import ReadAloudBtn from '@/components/ReadAloudBtn';
import {CrossSectionVisual,SectionShape} from './StarpathCrossSectionCard';
import {tileNodes} from './StarpathTessellationCard';
import {getCrossObject} from '@/data/activities/starpath/level6/crossSections';
import {operationLabel,key,transform,type Level6Item,type Operation,type L6Task} from '@/data/assessments/revisions/level6StarpathFiveForms';
import {emptyLevel6Response,type Level6Response} from '@/lib/starpath-level6-review';
import type {Point} from '@/data/activities/starpath/level5/coordinates';
import shared from '@/components/demo/GroundStarpathRedesign.module.css';
import styles from './Level6StarpathAssessmentCard.module.css';
const sx=(n:number)=>210+n*40,sy=(n:number)=>190-n*40;
function Polygon({points,image=false,open=false}:{points:Point[];image?:boolean;open?:boolean}){const Tag=open?'polyline':'polygon';return <Tag points={points.map(p=>`${sx(p.x)},${sy(p.y)}`).join(' ')} fill={open?'none':image?'#0891b233':'#7c3aed33'} stroke={image?'#087b93':'#6d28d9'} strokeWidth={3} strokeDasharray={image?'6 3':undefined}/>;}
function ordered(points:Point[]){const c={x:points.reduce((s,p)=>s+p.x,0)/points.length,y:points.reduce((s,p)=>s+p.y,0)/points.length};return [...points].sort((a,b)=>Math.atan2(a.y-c.y,a.x-c.x)-Math.atan2(b.y-c.y,b.x-c.x));}
function Plane({t,a,change}:{t:L6Task;a:Level6Response;change:(a:Level6Response)=>void}){
 const interactive=t.mode==='point'||t.mode==='shape';
 return <svg viewBox="0 0 410 410" className={styles.plane} role="group" aria-label="Cartesian plane with both axes numbered minus four to four">
 {Array.from({length:9},(_,i)=>i-4).map(n=><g key={n}><line x1={sx(n)} x2={sx(n)} y1={sy(-4)} y2={sy(4)} stroke={n===0?'#493964':'#ddd7e6'} strokeWidth={n===0?2:1}/><line x1={sx(-4)} x2={sx(4)} y1={sy(n)} y2={sy(n)} stroke={n===0?'#493964':'#ddd7e6'} strokeWidth={n===0?2:1}/><text x={sx(n)} y={sy(0)+17} textAnchor="middle" fill="#493964" fontSize="12" paintOrder="stroke" stroke="white" strokeWidth="3">{n}</text>{n!==0&&<text x={sx(0)-9} y={sy(n)+4} textAnchor="end" fill="#493964" fontSize="12" paintOrder="stroke" stroke="white" strokeWidth="3">{n}</text>}</g>)}
 <text x="380" y={sy(0)+4}>x</text><text x={sx(0)+8} y="20">y</text>
 {t.shape&&<Polygon points={t.shape} open={t.mode==='point'}/>}{t.image&&<><Polygon points={t.image} image/><text x={sx(t.shape![0].x)-15} y={sy(t.shape![0].y)+20}>A</text><text x={sx(t.image[0].x)+10} y={sy(t.image[0].y)+20}>B</text></>}
 {(t.operations||t.mode==='sequence')&&<><line x1={sx(0)} x2={sx(0)} y1={sy(-4)} y2={sy(4)} stroke="#b45309" strokeDasharray="5 4"/><text x={sx(0)+8} y={sy(0)-9} fill="#78350f">C</text></>}
 {t.points?.map(p=><g key={p.label}><circle cx={sx(p.point.x)} cy={sy(p.point.y)} r="5" fill="#6d28d9"/><text x={sx(p.point.x)+8} y={sy(p.point.y)-9} fontWeight="bold" fill="#30204c" paintOrder="stroke" stroke="white" strokeWidth="3">{p.label}</text></g>)}
 {a.points.length>0&&(t.mode==='shape'?<Polygon points={ordered(a.points)} image/>:<circle cx={sx(a.points[0].x)} cy={sy(a.points[0].y)} r="7" fill="#087b93"/>)}
 {t.mode==='sequence'&&a.commands.length>0&&<polygon points={a.commands.reduce((s,op)=>transform(s,op),t.shape!).map(p=>`${sx(p.x)},${sy(p.y)}`).join(' ')} fill="#fbbf2433" stroke="#b45309" strokeWidth={3} strokeDasharray="3 4"/>}
 {interactive&&Array.from({length:81},(_,i)=>({x:i%9-4,y:Math.floor(i/9)-4})).map(p=>{const selected=a.points.some(v=>key(v)===key(p));const toggle=()=>change({...a,points:t.mode==='point'?[p]:selected?a.points.filter(v=>key(v)!==key(p)):[...a.points,p]});return <circle key={key(p)} data-point={key(p)} cx={sx(p.x)} cy={sy(p.y)} r={15} fill="transparent" role="button" tabIndex={0} aria-label={`Point ${p.x}, ${p.y}`} aria-pressed={selected} onClick={toggle} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle();}}} className={styles.hit}/>;})}
 </svg>;
}
function Motif({step,single=false}:{step:number;single?:boolean}){return <svg viewBox={single?"140 0 120 130":"0 0 400 130"} style={single?{maxHeight:260}:undefined} className={styles.motif} role="img" aria-label={single?"An L-shaped motif with a marked corner":"Four copies of an L-shaped motif with a marked corner"}>
 {(single?[0]:[0,1,2,3]).map(i=><g key={i} transform={`translate(${single?200:55+i*95},65) rotate(${i*step*90})`}><path d="M-24 -24H24V-4H-4V24H-24Z" fill={i%2?'#c4b5fd':'#ddd0f6'} stroke="#5b3592" strokeWidth="2"/><circle cx="-17" cy="-17" r="4" fill="#78350f"/></g>)}{single&&step%2===0&&<><line x1="200" x2="200" y1="15" y2="115" stroke="#b45309" strokeDasharray="5 4"/><text x="208" y="115">C</text></>}
 </svg>;}
function Tiling({id,variant=0}:{id:string;variant?:number}){return <svg viewBox="0 0 320 190" className={styles.tiling} role="img" aria-label={`Repeated ${id} tiles`} overflow="hidden"><rect width="320" height="190" fill="#fff"/><g transform={id==='lshape'?`translate(${variant%2?320:0},${variant>2?190:0}) scale(${variant%2?-1:1},${variant>2?-1:1})`:undefined}>{tileNodes(id).map((n,i)=>n.pts?<polygon key={i} points={n.pts.map(p=>p.join(',')).join(' ')} fill={n.fill} stroke="#513777" strokeWidth={1.5}/>:<circle key={i} cx={n.cx} cy={n.cy} r={n.r} fill={n.fill} stroke="#513777"/>)}{id==='lshape'&&<rect x="38" y="58" width="40" height="60" stroke="#27133f" strokeWidth="3" fill="none"/>}</g></svg>;}
function Patch({t,a,change}:{t:L6Task;a:Level6Response;change:(a:Level6Response)=>void}){return <div className={styles.patch}>{t.orientations!.map((angle,i)=><div key={i}><svg viewBox="-2 -2 104 104" aria-label={`Square ${i+1}`} role="img"><rect width="100" height="100" fill="white" stroke="#513777"/><path d="M0 0V100H100Z" transform={`rotate(${angle*90},50,50)`} fill="#9c77d6" stroke="#513777"/><path d="M0 0V100H100Z" transform={`rotate(${a.orientations[i]*90},50,50)`} fill="#fbbf24" fillOpacity=".7" stroke="#78350f"/></svg><button onClick={()=>change({...a,orientations:a.orientations.map((n,j)=>i===j?(n+1)%4:n)})} aria-label={`Turn gold triangle in square ${i+1}`}>↻ Turn {i+1}</button></div>)}</div>;}
export default function Level6StarpathAssessmentCard({item,response:a,onChange:change}:{item:Level6Item;response:Level6Response;onChange:(a:Level6Response)=>void}){
 const t=item.task;
 let diagram;
 if(t.diagram==='solids')diagram=<div className={styles.solids}>{t.objects!.map((id,i)=><div key={i}><p>{String.fromCharCode(65+i)} · {getCrossObject(id).name}</p><CrossSectionVisual objectId={id} height={t.heights?.[i]??.5}/></div>)}</div>;
 if(t.diagram==='sections')diagram=<div className={styles.sections}>{t.sectionHeights!.map((height,i)=><div key={i}><p>{t.sectionHeights!.length===2?(i?'Upper':'Lower'):`Section ${i+1}`}</p><SectionShape object={getCrossObject(t.sectionObject!)} t={height}/></div>)}</div>;
 if(t.diagram==='cartesian')diagram=<Plane t={t} a={a} change={change}/>;
 if(t.diagram==='motif')diagram=<Motif step={t.turnStep??1} single={t.singleMotif}/>;
 if(t.diagram==='tiling')diagram=<Tiling id={t.tile!} variant={t.turnStep??0}/>;
 if(t.diagram==='patch')diagram=<Patch t={t} a={a} change={change}/>;
 const narration=t.diagram==='solids'?t.objects!.map((id,i)=>`${String.fromCharCode(65+i)}, ${getCrossObject(id).name}.`).join(' ')+' The gold plane shows a cut parallel to each base.':t.diagram==='cartesian'?'Both axes run from minus four to four, with one unit per interval. Purple is the original figure. Dashed blue is an image. C, when shown, marks the origin. For a program, the amber outline shows your current result.':t.diagram==='sections'?'Face-on sections, shown at the same scale. '+(t.sectionHeights!.length===2?'Lower section on the left; upper on the right.':'Three sections from bottom to top, left to right.'):t.diagram==='motif'?(t.singleMotif?'An L-shaped motif with a marked corner.'+((t.turnStep??0)%2===0?' The dashed vertical line through C is a fixed mirror.':''):'Four L-shaped motifs are shown from left to right. A dot marks the same corner on every copy.'):t.diagram==='patch'?'Six squares, numbered left to right across each row. Purple triangles stay fixed. Turn buttons rotate gold triangles a quarter turn clockwise about each square’s centre.':'A patch of repeated tiles. The pattern continues beyond the frame. '+(t.tile==='lshape'?'The dark rectangular outline marks a pair of L-shaped tiles.':'');
 const options=t.options&&<div className={styles.choices}>{t.options.map(o=><div className={shared.optionRow} key={o.id}><button data-option-id={o.id} aria-pressed={a.selected.includes(o.id)} onClick={()=>change({...a,selected:t.mode==='multi'?(a.selected.includes(o.id)?a.selected.filter(id=>id!==o.id):[...a.selected,o.id]):[o.id]})}>{o.label}</button><ReadAloudBtn text={o.label} kind="option" className={shared.voice}/></div>)}</div>;
 let controls=options;
 if(t.mode==='pair')controls=<div className={styles.pair}><p>Coordinates (x, y)</p><div>( <input aria-label="Horizontal coordinate x" inputMode="text" value={a.pair.x} onChange={e=>change({...a,pair:{...a.pair,x:e.target.value}})}/> , <input aria-label="Vertical coordinate y" inputMode="text" value={a.pair.y} onChange={e=>change({...a,pair:{...a.pair,y:e.target.value}})}/> )</div><ReadAloudBtn text="Enter the horizontal coordinate first and the vertical coordinate second. Include minus signs where needed." label="Read answer controls" className={shared.voice}/></div>;
 if(t.mode==='shape'||t.mode==='point')controls=<div className={styles.controls}><p>{a.points.length} {t.mode==='shape'?'vertices':'points'} selected</p><p>Tap a selected vertex again to remove it.</p><ReadAloudBtn text={`${a.points.length} points selected. Tap a selected vertex again to remove it. Reset clears your points.`} label="Read controls" className={shared.voice}/><button onClick={()=>change(emptyLevel6Response(item))}>Reset</button></div>;
 if(t.mode==='sequence')controls=<div className={styles.commands}>{(Object.keys(operationLabel) as Operation[]).map(op=><button key={op} disabled={a.commands.length===t.stepCount} onClick={()=>change({...a,commands:[...a.commands,op]})}>{operationLabel[op]}</button>)}<p>{a.commands.map((op,i)=>`${i+1}. ${operationLabel[op]}`).join(' → ')||'No commands yet'}</p><button onClick={()=>change({...a,commands:a.commands.slice(0,-1)})}>Undo</button><button onClick={()=>change(emptyLevel6Response(item))}>Reset</button><ReadAloudBtn text={`Commands available: ${Object.values(operationLabel).join('. ')}. Chosen: ${a.commands.map(op=>operationLabel[op]).join('. ')||'none'}. Undo removes the last command. Reset clears all commands.`} label="Read command controls" className={shared.voice}/></div>;
 if(t.mode==='tiles')controls=<div className={styles.controls}><p>Turn each gold partner to fill its square.</p><button onClick={()=>change(emptyLevel6Response(item))}>Reset patch</button><ReadAloudBtn text="Turn each gold partner to fill its square. Reset patch returns all gold triangles to their starting positions." label="Read controls" className={shared.voice}/></div>;
 return <><div className={shared.question}><h2 id="ground-question-heading">{item.prompt}</h2><ReadAloudBtn text={item.readAloudText} label="Read question" className={shared.voice}/></div><p className={shared.instruction}>{t.instruction}</p><div className={styles.split}><div className={styles.visual}>{diagram}<ReadAloudBtn text={narration} label="Read diagram" className={shared.voice}/></div><div>{controls}</div></div></>;
}
