"use client";
import type {CSSProperties} from 'react';
import ReadAloudBtn from '@/components/ReadAloudBtn';
import {buildSolid,type SolidFace,type SolidKind} from '@/data/activities/starpath/level5/solids';
import type {Cell} from '@/data/activities/starpath/level5/nets';
import type {Point,MoveDir} from '@/data/activities/starpath/level5/coordinates';
import {cellKey,pointKey,type Level5Item,type Option,type PlotTask} from '@/data/assessments/revisions/level5StarpathFiveForms';
import {follow,type Level5Response} from '@/lib/starpath-level5-review';
import shared from '@/components/demo/GroundStarpathRedesign.module.css';
import styles from './Level5StarpathAssessmentCard.module.css';

export function CubeNet({cells,labels=false,marked}:{cells:Cell[];labels?:boolean;marked?:number}){
 const minR=Math.min(...cells.map(c=>c.r)),minC=Math.min(...cells.map(c=>c.c));
 const w=(Math.max(...cells.map(c=>c.c))-minC+1)*48,h=(Math.max(...cells.map(c=>c.r))-minR+1)*48;
 return <svg viewBox={`-5 -5 ${w+10} ${h+10}`} className={styles.net} aria-hidden="true">{cells.map((c,i)=><g key={cellKey(c)}><rect x={(c.c-minC)*48} y={(c.r-minR)*48} width="48" height="48" fill={i===marked?'#fde68a':'#ddd0f6'} stroke="#5b3592" strokeWidth="2"/>{labels&&<text x={(c.c-minC)*48+24} y={(c.r-minR)*48+30} textAnchor="middle" fill="#30204c" fontSize="20" fontWeight="700">{String.fromCharCode(65+i)}</text>}</g>)}</svg>;
}
// Reuse the lesson's face dimensions and hinge tree to show an exact flat net.
export function SolidNet({kind,angle=0}:{kind:SolidKind;angle?:number}){
 const faces:{node:SolidFace;x:number;y:number}[]=[];
 function visit(node:SolidFace,x:number,y:number){faces.push({node,x,y});for(const child of node.children){const d=child.hinge!.dir;visit(child,x+(d==='E'?node.w:d==='W'?-child.w:0),y+(d==='S'?node.h:d==='N'?-child.h:0));}}
 visit(buildSolid(kind),0,0);const left=Math.min(...faces.map(f=>f.x)),top=Math.min(...faces.map(f=>f.y)),right=Math.max(...faces.map(f=>f.x+f.node.w)),bottom=Math.max(...faces.map(f=>f.y+f.node.h));const size=Math.max(right-left,bottom-top)+16;
 return <svg viewBox={`${-size/2} ${-size/2} ${size} ${size}`} className={styles.net} aria-hidden="true"><g transform={`rotate(${angle}) translate(${-((left+right)/2)} ${-((top+bottom)/2)})`}>{faces.map(({node,x,y})=>{const poly=node.clip?.match(/polygon\((.*)\)/)?.[1].split(',').map(pair=>{const [px,py]=pair.trim().split(/\s+/).map(v=>parseFloat(v));return `${x+px*node.w/100},${y+py*node.h/100}`;}).join(' ');return poly?<polygon key={node.id} points={poly} fill="#ddd0f6" stroke="#5b3592" strokeWidth="2"/>:<rect key={node.id} x={x} y={y} width={node.w} height={node.h} fill="#ddd0f6" stroke="#5b3592" strokeWidth="2"/>;})}</g></svg>;
}
const sx=(x:number)=>44+x*40,sy=(y:number)=>360-y*40;
function hull(points:Point[]){const sorted=[...points].sort((a,b)=>a.x-b.x||a.y-b.y);if(sorted.length<3)return sorted;const cross=(a:Point,b:Point,c:Point)=>(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);const lower:Point[]=[],upper:Point[]=[];for(const p of sorted){while(lower.length>1&&cross(lower.at(-2)!,lower.at(-1)!,p)<=0)lower.pop();lower.push(p);}for(const p of [...sorted].reverse()){while(upper.length>1&&cross(upper.at(-2)!,upper.at(-1)!,p)<=0)upper.pop();upper.push(p);}return [...lower.slice(0,-1),...upper.slice(0,-1)];}
function CoordinateGrid({t,a,onChange}:{t:PlotTask;a:Level5Response;onChange:(a:Level5Response)=>void}){
 const tappable=t.mode==='point'||t.mode==='shape';
 const drawShape=(points:Point[],image=false)=> <g><polygon points={points.map(p=>`${sx(p.x)},${sy(p.y)}`).join(' ')} fill={image?'#0891b230':'#7c3aed28'} stroke={image?'#087b93':'#6d28d9'} strokeWidth="3" strokeDasharray={image?'6 3':undefined}/>{points.map(p=><circle key={pointKey(p)} cx={sx(p.x)} cy={sy(p.y)} r="4" fill={image?'#087b93':'#6d28d9'}/>)}</g>;
 const markers=[...(t.points??[]),...(t.start?[{label:'S',point:t.start}]:[]),...(t.via?[{label:'V',point:t.via}]:[]),...(t.goal?[{label:'F',point:t.goal}]:[])];
 return <svg viewBox="0 0 408 414" className={styles.plane} role="group" aria-label="Coordinate grid from zero to eight on both axes">
  {Array.from({length:9},(_,i)=><g key={i}><line x1={sx(i)} x2={sx(i)} y1={sy(0)} y2={sy(8)} stroke="#d8d3e5"/><line x1={sx(0)} x2={sx(8)} y1={sy(i)} y2={sy(i)} stroke="#d8d3e5"/>{['x','y'].map(axis=>{const x=axis==='x'?sx(i):22,y=axis==='x'?384:sy(i)+5;const missing=t.mode==='axes'&&t.axisValues!.includes(i);return missing?<foreignObject key={axis} x={x-15} y={y-18} width="30" height="28"><input className={styles.tickInput} aria-label={`${axis==='x'?'Horizontal':'Vertical'} missing label ${t.axisValues!.indexOf(i)+1} from ${axis==='x'?'left':'bottom'}`} inputMode="numeric" maxLength={1} value={a.labels[axis+i]??''} onChange={e=>onChange({...a,labels:{...a.labels,[axis+i]:e.target.value}})}/></foreignObject>:<text key={axis} x={x} y={y} textAnchor="middle" fill="#493964" fontSize="14">{i}</text>;})}</g>)}
  <path d={`M${sx(0)} ${sy(8)-10}V${sy(0)}H${sx(8)+10}`} fill="none" stroke="#493964" strokeWidth="2"/>
  <text x="190" y="407" textAnchor="middle" fontSize="13" fill="#493964">Horizontal (x)</text><text x="44" y="20" fontSize="13" fill="#493964">Vertical (y)</text>
  {t.shape&&drawShape(t.shape)}{t.image&&drawShape(t.image,true)}
  {t.mirror&&<line x1={t.mirror.axis==='vertical'?sx(t.mirror.at):sx(0)} x2={t.mirror.axis==='vertical'?sx(t.mirror.at):sx(8)} y1={t.mirror.axis==='horizontal'?sy(t.mirror.at):sy(0)} y2={t.mirror.axis==='horizontal'?sy(t.mirror.at):sy(8)} stroke="#b45309" strokeWidth="2" strokeDasharray="7 5"/>}
  {t.centre&&<g><path d={`M${sx(t.centre.x)-6} ${sy(t.centre.y)}h12 M${sx(t.centre.x)} ${sy(t.centre.y)-6}v12`} stroke="#b45309" strokeWidth="2"/><text x={sx(t.centre.x)+9} y={sy(t.centre.y)+17} fontSize="14" fill="#78350f">C</text></g>}
  {t.mode==='route'&&a.moves.length>0&&<polyline points={follow(t.start!,a.moves).map(p=>`${sx(p.x)},${sy(p.y)}`).join(' ')} fill="none" stroke="#0891b2" strokeWidth="3"/>}
  {markers.map(m=><g key={m.label}><circle cx={sx(m.point.x)} cy={sy(m.point.y)} r="6" fill="#6d28d9"/><text x={sx(m.point.x)+9} y={sy(m.point.y)-9} fontSize="15" fontWeight="700" fill="#30204c">{m.label}</text></g>)}
  {t.blocked?.map(p=><g key={pointKey(p)}><circle cx={sx(p.x)} cy={sy(p.y)} r="11" fill="#fee2e2" stroke="#991b1b"/><text x={sx(p.x)} y={sy(p.y)+5} textAnchor="middle" fill="#991b1b">×</text></g>)}
  {a.points.length>0&&(t.mode==='shape'?drawShape(hull(a.points),true):<circle cx={sx(a.points[0].x)} cy={sy(a.points[0].y)} r="7" fill="#0891b2"/>)}
  {tappable&&Array.from({length:81},(_,i)=>{const p={x:i%9,y:Math.floor(i/9)},selected=a.points.some(v=>pointKey(v)===pointKey(p));const toggle=()=>onChange({...a,points:t.mode==='point'?[p]:selected?a.points.filter(v=>pointKey(v)!==pointKey(p)):[...a.points,p]});return <circle key={i} data-point={pointKey(p)} cx={sx(p.x)} cy={sy(p.y)} r="14" fill="transparent" role="button" tabIndex={0} aria-label={`Point ${p.x}, ${p.y}`} aria-pressed={selected} onClick={toggle} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle();}}} className={styles.hit}/>;})}
 </svg>;
}
export default function Level5StarpathAssessmentCard({item,response:a,onChange}:{item:Level5Item;response:Level5Response;onChange:(a:Level5Response)=>void}){
 const t=item.task;
 const choices=(options:Option[])=><div className={options.some(o=>o.cells)?styles.netChoices:styles.choices}>{options.map(o=><div className={shared.optionRow} key={o.id}><button data-option-id={o.id} aria-pressed={a.selected===o.id} onClick={()=>onChange({...a,selected:o.id})}>{o.cells&&<CubeNet cells={o.cells}/>}<span>{o.label}</span></button><ReadAloudBtn text={o.cells?`${o.label}. ${o.cells.map(c=>`Square at row ${c.r+1}, column ${c.c+1}`).join('. ')}`:o.label} kind="option" className={shared.voice}/></div>)}</div>;
 let body;
 if(item.kind==='net'){
  const n=item.task;
  const diagram=<div className={styles.visual}>{n.solid&&<div className={styles.solidPair}><div>{n.secondSolid&&<p>Net A</p>}<SolidNet kind={n.solid} angle={n.angle}/></div>{n.secondSolid&&<div><p>Net B</p><SolidNet kind={n.secondSolid} angle={n.angle}/></div>}</div>}{n.cells&&<><CubeNet cells={n.cells} labels={n.marked!==undefined} marked={n.marked}/>{n.mode==='build'&&<p>Example — make a different net</p>}</>}<ReadAloudBtn text={n.cells?`${n.mode==='build'?'Example net. ':''}${n.cells.map((c,i)=>`${n.marked!==undefined?`Face ${String.fromCharCode(65+i)}`:'Square'} at row ${c.r+1}, column ${c.c+1}`).join('. ')}. Rows count from the top, columns from the left.`:`${n.secondSolid?'Net A is on the left. Net B is on the right. ':''}Solid lines show the edges of the joined faces. Imagine folding at the shared edges.`} label="Read diagram" className={shared.voice}/></div>;
  const construction=<div className={styles.builder}><div className={styles.netBoard}>{Array.from({length:25},(_,i)=>{const c={r:Math.floor(i/5),c:i%5},locked=(n.seeds??[]).some(p=>cellKey(p)===cellKey(c)),selected=a.cells.some(p=>cellKey(p)===cellKey(c));return <button key={i} data-cell={cellKey(c)} aria-label={`Row ${c.r+1}, column ${c.c+1}${locked?', given square':''}`} aria-pressed={selected} aria-disabled={locked} onClick={()=>{if(!locked)onChange({...a,cells:selected?a.cells.filter(p=>cellKey(p)!==cellKey(c)):a.cells.length<6?[...a.cells,c]:a.cells});}} style={{background:selected?'var(--selected)':'white',color:selected?'white':undefined}}>{locked?'●':''}</button>;})}</div><p>{a.cells.length}/6 squares selected</p><button onClick={()=>onChange({...a,cells:[...(n.seeds??[])]})}>Reset net</button><ReadAloudBtn text={`Five by five construction grid. ${a.cells.length} of six squares selected. Filled squares are selected. A dot marks a given square. Reset net removes your additions.`} label="Read controls" className={shared.voice}/></div>;
  body=n.mode==='choice'?(n.options!.some(o=>o.cells)?choices(n.options!):<div className={styles.split}>{diagram}{choices(n.options!)}</div>):<div className={styles.split}>{n.cells?diagram:<div className={styles.visual}><h3>Complete the net</h3><p>Keep the five marked faces.</p><ReadAloudBtn text="Complete the net. Keep the five marked faces." className={shared.voice}/></div>}{construction}</div>;
 }else{
  const p=item.task;const legend=p.shape?(p.image?'Solid purple: shape A. Dashed blue: image B.':p.mode==='shape'?'Solid purple: original shape. Dashed blue: your image.':'Solid purple: shape to test.'):'Each grid interval is one unit.';
  const diagram=<div className={styles.visual}><CoordinateGrid t={p} a={a} onChange={onChange}/></div>;
  const information=<div className={styles.diagramInfo}><p>{legend}</p><ReadAloudBtn text={`${legend} The horizontal x axis runs left to right; the vertical y axis runs bottom to top. ${p.mode==='axes'?'Both axes have missing labels.':'Both axes are numbered zero to eight.'} ${p.mirror?`The dashed amber line is the mirror line at ${p.mirror.axis==='vertical'?'x':'y'} equals ${p.mirror.at}.`:''} ${p.centre?'C marks the fixed centre of rotation.':''} ${p.mode==='route'?'S is start, V is the checkpoint, F is finish. The cross is blocked.':''}`} label="Read diagram" className={shared.voice}/></div>;
  const controls=p.mode==='choice'?choices(p.options!):p.mode==='pair'?<div className={styles.pair}><p>Coordinates (x, y)</p><div><span>(</span><input aria-label="Horizontal coordinate x" inputMode="numeric" value={a.pair.x} onChange={e=>onChange({...a,pair:{...a.pair,x:e.target.value}})}/><span>,</span><input aria-label="Vertical coordinate y" inputMode="numeric" value={a.pair.y} onChange={e=>onChange({...a,pair:{...a.pair,y:e.target.value}})}/><span>)</span></div><ReadAloudBtn text="Enter coordinates. First box: horizontal x. Second box: vertical y." label="Read answer controls" className={shared.voice}/></div>:p.mode==='route'?<div className={styles.route}><p>S → V → F</p><div>{(['up','left','down','right'] as MoveDir[]).map(d=><button key={d} aria-label={`Add ${d}`} onClick={()=>onChange({...a,moves:[...a.moves,d]})}>{({up:'↑',down:'↓',left:'←',right:'→'})[d]}</button>)}</div><p>{a.moves.join(' → ')||'No moves yet'}</p><p>{a.moves.length}/{p.maxMoves} moves</p><button onClick={()=>onChange({...a,moves:a.moves.slice(0,-1)})}>Undo</button><button onClick={()=>onChange({...a,moves:[]})}>Clear route</button><ReadAloudBtn text={`Start, checkpoint, finish. Add up, left, down or right, one unit per move. ${a.moves.length} moves chosen: ${a.moves.join(', ')}. Undo removes the last move. Clear route removes all moves.`} label="Read route controls" className={shared.voice}/></div>:<div className={styles.builder}><p>{p.mode==='axes'?'Enter the missing numbers directly on the axes.':p.mode==='shape'?`${a.points.length} vertices selected`:'Tap a grid intersection.'}</p><button onClick={()=>onChange({...a,points:[],labels:{}})}>Reset</button><ReadAloudBtn text={p.mode==='axes'?'Enter the missing numbers directly on the axes. Reset clears your entries.':`Tap grid intersections. ${a.points.length} points selected. Reset clears your points.`} label="Read controls" className={shared.voice}/></div>;
  body=<div className={styles.split}>{diagram}<div>{controls}{information}</div></div>;
 }
 return <div style={{'--diagram-purple':'#6d28d9'} as CSSProperties}><div className={shared.question}><h2 id="ground-question-heading">{item.prompt}</h2><ReadAloudBtn text={item.readAloudText} label="Read question" className={shared.voice}/></div><p className={shared.instruction}>{t.instruction}</p>{body}</div>;
}
