'use client';
import ReadAloudBtn from '@/components/ReadAloudBtn';
import {CubeNet} from './Level5StarpathAssessmentCard';
import {CubeModel} from './Level3StarpathAssessmentCard';
import {move7,MOVE7_LABELS,type Level7Item,type Polygon7,type Task7,type P7} from '@/data/assessments/revisions/level7StarpathFiveForms';
import {emptyLevel7Response,type Level7Response} from '@/lib/starpath-level7-review';
import shared from '@/components/demo/GroundStarpathRedesign.module.css';
import styles from './Level7StarpathAssessmentCard.module.css';
function Polygon({spec}:{spec:Polygon7}){const ps=spec.points,minX=Math.min(...ps.map(p=>p.x)),maxX=Math.max(...ps.map(p=>p.x)),minY=Math.min(...ps.map(p=>p.y)),maxY=Math.max(...ps.map(p=>p.y)),scale=Math.min(180/(maxX-minX||1),140/(maxY-minY||1));const pts=ps.map(p=>({x:130+(p.x-(minX+maxX)/2)*scale,y:105+(p.y-(minY+maxY)/2)*scale}));return <figure><svg viewBox="0 0 260 210" role="img" aria-label={spec.caption}><polygon points={pts.map(p=>`${p.x},${p.y}`).join(' ')} fill="#ddd0f6" stroke="#67419a" strokeWidth="3"/>{spec.sideLabels?.map((label,i)=>{const p=pts[i],n=pts[(i+1)%pts.length],x=(p.x+n.x)/2,y=(p.y+n.y)/2,dx=x-pts.reduce((sum,p)=>sum+p.x,0)/pts.length,dy=y-pts.reduce((sum,p)=>sum+p.y,0)/pts.length,d=Math.hypot(dx,dy)||1;return <text key={i} x={x+dx/d*17} y={y+dy/d*17} textAnchor="middle" dominantBaseline="middle">{label}</text>;})}{spec.angles?.map((label,i)=>label&&<text key={i} x={pts[i].x+(130-pts[i].x)*.25} y={pts[i].y+(105-pts[i].y)*.25} textAnchor="middle">{label}</text>)}</svg><figcaption>{spec.caption}{spec.sideLabels&&<span> Side lengths: {spec.sideLabels.join(', ')}.</span>}</figcaption></figure>;}
function Profile({values,footprint=false}:{values:number[];footprint?:boolean}){return footprint?<div className={styles.footprint} aria-label="Footprint: two rows, back row first">{values.map((v,i)=><span key={i} style={{background:v?'#b79adc':'white'}}>{v?'■':'·'}</span>)}</div>:<div className={styles.profile} aria-label={`Column heights: ${values.join(', ')}`}>{values.map((v,i)=><div key={i}><span style={{height:Math.max(2,v*23),background:'#b79adc'}}/><small>{v}</small></div>)}</div>;}
function Plans({t}:{t:Task7}){return <div className={styles.plans}><figure><p>Height plan · Back</p><div className={styles.heightPlan}>{t.heights!.map((n,i)=><span key={i}>{n}</span>)}</div><figcaption>Front<br/>Left → Right</figcaption></figure>{t.showModel&&<figure><CubeModel model={{cols:t.cols!,rows:t.rows!,height:Math.max(...t.heights!)}} heights={t.heights} showColumnIds={false} label="Given model built from equal cubes"/><figcaption>Isometric view<br/>Use the plan labels for directions.</figcaption></figure>}</div>;}
function Plane({t,a,onChange}:{t:Task7;a:Level7Response;onChange:(a:Level7Response)=>void}){const px=(x:number)=>210+x*28,py=(y:number)=>210-y*28;const draw=(ps:P7[],colour:string,dash?:string)=>ps.length===1?<circle cx={px(ps[0].x)} cy={py(ps[0].y)} r="5" fill={colour}/>:<polygon points={ps.map(p=>`${px(p.x)},${py(p.y)}`).join(' ')} fill={colour+'18'} stroke={colour} strokeWidth="3" strokeDasharray={dash}/>;const selected=[...a.points];if(selected.length>2){const x=selected.reduce((s,p)=>s+p.x,0)/selected.length,y=selected.reduce((s,p)=>s+p.y,0)/selected.length;selected.sort((p,q)=>Math.atan2(p.y-y,p.x-x)-Math.atan2(q.y-y,q.x-x));}return <svg viewBox="0 0 420 420" className={styles.plane} role="group" aria-label="Cartesian plane: both axes from minus six to six">
 {Array.from({length:13},(_,i)=>i-6).map(n=><g key={n}><path d={`M${px(n)} 42V378M42 ${py(n)}H378`} stroke={n===0?'#665076':'#ddd5e7'} strokeWidth={n===0?2:1}/><text x={px(n)} y="398" textAnchor="middle">{n}</text><text x="25" y={py(n)+4} textAnchor="middle">{n}</text></g>)}<text x="392" y="205">x</text><text x="215" y="25">y</text>
 {t.mirrorX?.map(x=><g key={x}><line x1={px(x)} x2={px(x)} y1="42" y2="378" stroke="#a36a1b" strokeDasharray="5 4"/><text x={px(x)+5} y="36">x={x}</text></g>)}
 {t.shape&&draw(t.shape,'#7045a3')}{t.shape&&<text x={px(t.shape[0].x)-12} y={py(t.shape[0].y)-10}>{t.shape.length===1?'P':'A'}</text>}{t.image&&draw(t.image,'#087f9c','5 4')}{t.image&&<text x={px(t.image[0].x)+8} y={py(t.image[0].y)-10}>B</text>}{t.centre&&<g><circle cx={px(t.centre.x)} cy={py(t.centre.y)} r="4" fill="#a36a1b"/><text x={px(t.centre.x)+8} y={py(t.centre.y)-8}>C</text></g>}
 {selected.length>1&&draw(selected,'#a36a1b','4 3')}{selected.map(p=><circle key={`${p.x},${p.y}`} cx={px(p.x)} cy={py(p.y)} r="5" fill="#a36a1b"/>)}{t.mode==='program'&&a.commands.length>0&&draw(a.commands.reduce((ps,op)=>move7(ps,op),t.shape!),'#a36a1b','3 3')}
 {t.mode==='points'&&Array.from({length:169},(_,i)=>({x:i%13-6,y:Math.floor(i/13)-6})).map(p=>{const key=`${p.x},${p.y}`,has=a.points.some(q=>q.x===p.x&&q.y===p.y),choose=()=>onChange({...a,points:has?a.points.filter(q=>q.x!==p.x||q.y!==p.y):t.expected!.length===1?[p]:[...a.points,p]});return <circle key={key} data-point={key} cx={px(p.x)} cy={py(p.y)} r="12" fill="transparent" role="button" tabIndex={0} aria-label={`Point ${p.x}, ${p.y}`} aria-pressed={has} className={styles.hit} onClick={choose} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose();}}}/>;})}
 </svg>;}
export default function Level7StarpathAssessmentCard({item,response:a,onChange}:{item:Level7Item;response:Level7Response;onChange:(a:Level7Response)=>void}){const t=item.task;const narration=t.diagram==='plans'?`Height plan: back row ${t.heights!.slice(0,3).join(', ')}; front row ${t.heights!.slice(3).join(', ')}. Entries count cubes in each column; zero means empty. The isometric view shows the same model.`:t.diagram==='net'?`Six labelled squares. ${t.cells!.map((p,i)=>`${String.fromCharCode(65+i)} at row ${p.r+1}, column ${p.c+1}`).join('. ')}.`:t.diagram==='plane'?`Both axes run from minus six to six. Purple ${t.shape!.length===1?'point P':'triangle A'}: ${t.shape!.map(p=>`(${p.x}, ${p.y})`).join(', ')}. ${t.image?`Dashed blue B: ${t.image.map(p=>`(${p.x}, ${p.y})`).join(', ')}.`:''} ${t.centre?`C is (${t.centre.x}, ${t.centre.y}).`:''} ${t.mirrorX?`Mirror lines: ${t.mirrorX.map(x=>`x equals ${x}`).join(', ')}.`:''} Amber shows your response.`:[...(t.flow??[]),...(t.polygons??[]).map(p=>p.caption+(p.sideLabels?` Side lengths: ${p.sideLabels.join(', ')}.`:''))].join(' ');
 const diagram=<div className={styles.visual}>{t.diagram==='net'&&<CubeNet cells={t.cells!} marked={t.marked} labels/>}{t.diagram==='plans'&&<Plans t={t}/>} {t.diagram==='plane'&&<Plane t={t} a={a} onChange={onChange}/>} {t.polygons&&<div className={styles.polygons}>{t.polygons.map((p,i)=><Polygon key={i} spec={p}/>)}</div>} {t.flow&&<ol className={styles.flow}>{t.flow.map((s,i)=><li key={i}>{s}</li>)}</ol>}{t.diagram!=='none'&&<ReadAloudBtn text={narration} label="Read diagram" className={shared.voice}/>}</div>;
 const choiceGrid=t.options?.some(o=>o.cells||o.polygon||o.profile)?styles.pictureChoices:styles.choices;
 let controls=t.options&&<div className={choiceGrid}>{t.options.map(o=><div className={shared.optionRow} key={o.id}><button data-option-id={o.id} aria-pressed={a.selected.includes(o.id)} onClick={()=>onChange({...a,selected:t.mode==='multi'?(a.selected.includes(o.id)?a.selected.filter(id=>id!==o.id):[...a.selected,o.id]):[o.id]})}>{o.cells&&<CubeNet cells={o.cells}/>} {o.polygon&&<Polygon spec={o.polygon}/>} {o.profile&&<Profile values={o.profile} footprint={o.profile.length===6}/>}<span>{o.label}</span></button><ReadAloudBtn text={`${o.label}. ${o.cells?o.cells.map(p=>`Square at row ${p.r+1}, column ${p.c+1}`).join('. '):o.polygon?o.polygon.caption:o.profile?`${o.profile.length===6?'Occupied squares, back row then front row. One means occupied, zero means empty.':'Column heights:'} ${o.profile.join(', ')}`:''}`} kind="option" className={shared.voice}/></div>)}</div>;
 if(t.mode==='number'||t.mode==='pair')controls=<div className={styles.inputs}>{t.mode==='number'?<label>Number of cubes<input aria-label="Number of cubes" inputMode="numeric" value={a.value} onChange={e=>onChange({...a,value:e.target.value})}/></label>:<><label>Change in x<input aria-label="Change in x" inputMode="text" value={a.pair.x} onChange={e=>onChange({...a,pair:{...a.pair,x:e.target.value}})}/></label><label>Change in y<input aria-label="Change in y" inputMode="text" value={a.pair.y} onChange={e=>onChange({...a,pair:{...a.pair,y:e.target.value}})}/></label></>}<ReadAloudBtn text={t.mode==='number'?'Enter the total number of cubes.':'Enter the signed change in x and the signed change in y.'} label="Read answer controls" className={shared.voice}/></div>;
 if(t.mode==='points'||t.mode==='program')controls=<div className={styles.tools}>{t.mode==='points'?<p>{a.points.length} of {t.expected!.length} vertices selected</p>:<><div>{(['reflectX','reflectY'] as const).map(op=><button key={op} disabled={a.commands.length===t.programLength} onClick={()=>onChange({...a,commands:[...a.commands,op]})}>{MOVE7_LABELS[op]}</button>)}</div><p>{a.commands.map((op,i)=>`${i+1}. ${MOVE7_LABELS[op]}`).join(' → ')||'No commands yet'}</p><button disabled={!a.commands.length} onClick={()=>onChange({...a,commands:a.commands.slice(0,-1)})}>Undo</button></>}<button onClick={()=>onChange(emptyLevel7Response(item))}>Reset</button><ReadAloudBtn text={t.mode==='points'?`Tap the ${t.expected!.length} final vertices. Tap a selected point to remove it. Reset clears your response.`:'Choose Reflect in the x-axis or Reflect in the y-axis twice. Undo removes the last command. Reset clears both commands.'} label="Read controls" className={shared.voice}/></div>;
 if(t.mode==='sort')controls=<div className={styles.sort}>{t.sortRows!.map(r=><div key={r.id}><strong>{r.label}</strong>{r.polygon&&<Polygon spec={r.polygon}/>}<select aria-label={`Output for ${r.label}`} value={a.assignments[r.id]??''} onChange={e=>onChange({...a,assignments:{...a.assignments,[r.id]:e.target.value}})}><option value="">Choose output</option>{t.categories!.map(s=><option key={s}>{s}</option>)}</select><ReadAloudBtn text={`${r.label}. ${r.polygon?.caption} Choose ${t.categories!.join(', or ')}.`} label={`Read ${r.label}`} className={shared.voice}/></div>)}</div>;
 if(t.mode==='decisions')controls=<div className={styles.decisions}>{t.decisionLabels!.map((label,i)=><label key={label}>{label}<select aria-label={label} value={a.decisions[i]??''} onChange={e=>{const decisions=[...a.decisions];decisions[i]=e.target.value;onChange({...a,decisions});}}><option value="">Choose decision</option>{t.decisionChoices!.map(s=><option key={s}>{s}</option>)}</select></label>)}<ReadAloudBtn text={`Complete decisions 1, 2 and 3. Available decisions: ${t.decisionChoices!.join(' ')}`} label="Read decision choices" className={shared.voice}/></div>;
 return <><div className={shared.question}><h2 id="ground-question-heading">{item.prompt}</h2><ReadAloudBtn text={item.readAloudText} label="Read question" className={shared.voice}/></div><p className={shared.instruction}>{t.instruction}</p>{t.diagram==='none'?controls:<div className={styles.split}>{diagram}{controls}</div>}</>;
}
