"use client";
import {useId,useState} from 'react';
import {BookOpen,Flag,House,TreePine,Waves,Volleyball} from 'lucide-react';
import ReadAloudBtn from '@/components/ReadAloudBtn';
import {L3_OBJECTS,type L3ObjectId} from '@/data/activities/starpath/level3/l3-objects';
import {ARROWS,type Landmark} from '@/data/assessments/revisions/level2StarpathFiveForms';
import type {Level3Item,Choice,BlockModel} from '@/data/assessments/revisions/level3StarpathFiveForms';
import {constraintText,mapItem,type Level3Response} from '@/lib/starpath-level3-review';
import {sameCell} from '@/lib/starpath-level1-review';
import Level2StarpathAssessmentCard from './Level2StarpathAssessmentCard';
import shared from '@/components/demo/GroundStarpathRedesign.module.css';
import styles from './Level3StarpathAssessmentCard.module.css';
const icons={gate:Flag,book:BookOpen,building:House,tree:TreePine,water:Waves,ball:Volleyball};
function Symbol({landmark}:{landmark:Landmark}){const Icon=icons[landmark.icon];return <Icon aria-hidden="true"/>;}
function Solid({id}:{id:L3ObjectId}){
 const unique=useId().replace(/[^a-zA-Z0-9]/g,'');
 // The lesson pyramid exposes its back face as solid. Here the hidden base edges
 // are dashed so the projection is a closed square-based pyramid.
 const pyramid='<path d="M27 84L60 68L94 84M60 68L60 20" fill="none" stroke="#78350f" stroke-width="1.5" stroke-dasharray="4 3"/><polygon points="60,20 27,84 60,101" fill="#fbbf24" fill-opacity=".8" stroke="#78350f" stroke-width="2"/><polygon points="60,20 94,84 60,101" fill="#d97706" fill-opacity=".8" stroke="#78350f" stroke-width="2"/>';
 let inner=id==='pyramid'?pyramid:L3_OBJECTS[id].inner;
 inner=inner.replace(/id="([^"]+)"/g,`id="${unique}-$1"`).replace(/url\(#([^)]+)\)/g,`url(#${unique}-$1)`);
 return <svg className={styles.solid} viewBox="0 0 120 120" aria-hidden="true" dangerouslySetInnerHTML={{__html:inner}}/>;
}
export function CubeModel({model,heights,showColumnIds=true,label}:{model:BlockModel;heights?:number[];showColumnIds?:boolean;label?:string}){
 const cells=Array.from({length:model.rows*model.cols},(_,i)=>({r:Math.floor(i/model.cols),c:i%model.cols,h:heights?.[i]??model.height})).sort((a,b)=>a.r+a.c-b.r-b.c);
 return <svg className={styles.cubeArt} viewBox={`${-model.rows*24-12} ${75-Math.max(model.height,...(heights??[]))*24-12} ${(model.rows+model.cols)*24+24} ${(model.rows+model.cols-2)*12+48+Math.max(model.height,...(heights??[]))*24}`} role="img" aria-label={label??(heights?'Your cube model':'Solid model built from equal cubes')}>{cells.map(({r,c,h})=>{const x=(c-r)*24,y=75+(c+r)*12;return <g key={`${r}-${c}`}><polygon points={`${x},${y} ${x+24},${y+12} ${x},${y+24} ${x-24},${y+12}`} fill="#f1edf8" stroke="#bcafd0" strokeDasharray="3 2"/>{Array.from({length:h},(_,i)=>{const top=y-(i+1)*24;return <g key={i} stroke="#493178" strokeWidth="1.5" strokeLinejoin="round"><polygon points={`${x-24},${top+12} ${x},${top+24} ${x},${top+48} ${x-24},${top+36}`} fill="#a78bfa"/><polygon points={`${x},${top+24} ${x+24},${top+12} ${x+24},${top+36} ${x},${top+48}`} fill="#8060c0"/><polygon points={`${x},${top} ${x+24},${top+12} ${x},${top+24} ${x-24},${top+12}`} fill="#ddd0fc"/></g>;})}{heights&&showColumnIds&&<g><circle cx={x} cy={y-h*24+12} r="8" fill="white"/><text x={x} y={y-h*24+16} textAnchor="middle" fontSize="11" fill="#493178">{r*model.cols+c+1}</text></g>}</g>;})}</svg>;
}
function RoomViews({variant}:{variant:number}){const x=variant%2?130:60,roof=variant%3===0?'60,70 150,15 240,70':variant%3===1?'60,70 60,35 240,35 240,70':'60,70 150,40 240,70';return <div className={styles.views}><figure><svg viewBox="0 0 300 190" role="img" aria-label={`Plan view: a room boundary with a table on the ${variant%2?'right':'left'} and chairs around it; doorway at bottom.`}><rect x="35" y="15" width="230" height="155" rx="4" fill="#f0ebfa" stroke="#51416b" strokeWidth="5"/><path d="M120 170h60" stroke="#fffefa" strokeWidth="7"/><path d="M120 170v-40a40 40 0 0 1 40 40" fill="none" stroke="#86769d" strokeWidth="2"/><rect x={x} y="55" width="100" height="55" rx="4" fill="#e6ba65" stroke="#856328" strokeWidth="3"/>{[x+15,x+65].map(px=><g key={px}><rect x={px} y="35" width="20" height="15" fill="#b39bdc"/><rect x={px} y="115" width="20" height="15" fill="#b39bdc"/></g>)}<text x="150" y="187" textAnchor="middle" fontSize="13">Doorway</text></svg><figcaption>Plan view · from above</figcaption></figure><figure><svg viewBox="0 0 300 190" role="img" aria-label={`Front view: the outside wall, a ${variant%3===1?'flat':'triangular'} roof, a tall doorway and two windows. Furniture inside is not shown.`}><rect x="60" y="70" width="180" height="105" fill="#d6e9e3" stroke="#345c4f" strokeWidth="4"/><polygon points={roof} fill="#b39bdc" stroke="#51416b" strokeWidth="4"/><rect x="130" y="115" width="40" height="60" fill="#e6ba65" stroke="#856328" strokeWidth="3"/><rect x="80" y="95" width="30" height="30" fill="#a5dcef" stroke="#345c4f" strokeWidth="3"/><rect x="190" y="95" width="30" height="30" fill="#a5dcef" stroke="#345c4f" strokeWidth="3"/></svg><figcaption>Front view · from outside</figcaption></figure></div>;}
export default function Level3StarpathAssessmentCard({item,response:a,onChange}:{item:Level3Item;response:Level3Response;onChange:(a:Level3Response)=>void}){
 const [active,setActive]=useState<string|null>(null);
 if(item.kind==='map')return <Level2StarpathAssessmentCard item={mapItem(item)} response={a.map} onChange={map=>onChange({...a,map})}/>;
 const t=item.task;
 const choose=(id:string)=>onChange({...a,selected:t.mode==='multi'?(a.selected.includes(id)?a.selected.filter(x=>x!==id):[...a.selected,id]):[id]});
 const choices=(opts:Choice[],reason=false)=><div className={opts.some(o=>o.object)?styles.choices:reason?shared.reasonChoices:styles.textChoices}>{opts.map((o,i)=>o.object?<div className={styles.choice} key={o.id}><button data-option-id={o.id} aria-label={`Object ${String.fromCharCode(65+i)}`} aria-pressed={a.selected.includes(o.id)} onClick={()=>choose(o.id)}><span className={styles.letter}>{String.fromCharCode(65+i)}</span><Solid id={o.object}/></button></div>:<div className={shared.optionRow} key={o.id}><button data-option-id={reason?undefined:o.id} data-reason-id={reason?o.id:undefined} aria-pressed={reason?a.reason===o.id:a.selected.includes(o.id)} onClick={()=>reason?onChange({...a,reason:o.id}):choose(o.id)}>{o.label}</button><ReadAloudBtn text={o.label!} kind="option" className={shared.voice}/></div>)}</div>;
 const header=<><div className={shared.question}><h2 id="ground-question-heading">{t.prompt}</h2><ReadAloudBtn text={item.readAloudText} label="Read question" className={shared.voice}/></div>{t.instruction&&<p className={shared.instruction}>{t.instruction}</p>}</>;
 if(item.kind==='solid'){
  const s=item.task;
  return <>{header}{s.build?<div className={styles.split}><div className={shared.visualPanel}><CubeModel model={s.build} heights={a.heights}/><ReadAloudBtn text={`Your model has ${s.build.rows} rows of columns and ${s.build.cols} columns across. ${a.heights.map((h,i)=>`Base square ${i+1}: ${h} cubes high.`).join(' ')}`} label="Read model" className={shared.voice}/></div><div><h3 className={styles.builderTitle}>Build each column</h3><div className={styles.base} style={{gridTemplateColumns:`repeat(${s.build.cols},minmax(0,1fr))`}}>{a.heights.map((h,i)=><div key={i} className={styles.column}>Base square {i+1}<div><button aria-label={`Remove cube ${i+1}`} disabled={h===0} onClick={()=>onChange({...a,heights:a.heights.map((n,j)=>j===i?n-1:n)})}>−</button><strong>{h}</strong><button aria-label={`Add cube ${i+1}`} disabled={h===4} onClick={()=>onChange({...a,heights:a.heights.map((n,j)=>j===i?n+1:n)})}>+</button></div></div>)}</div><ReadAloudBtn text="Use plus to add a cube to a column, or minus to remove one. Columns match the base squares, left to right in each row." label="Read controls" className={shared.voice}/></div></div>:<>
   {s.objects||s.models?<div className={styles.split}><div><div className={s.objects?styles.visuals:styles.models}>{s.objects?.map((id,i)=><Solid key={i} id={id}/>)}{s.models?.map((m,i)=><figure className={styles.model} key={i}><CubeModel model={m}/>{s.models!.length>1&&<figcaption>Model {'AB'[i]}</figcaption>}</figure>)}</div><ReadAloudBtn text={s.models?s.models.map((m,i)=>`Model ${s.models!.length>1?'AB'[i]:''}: ${m.rows} rows, ${m.cols} cubes across, ${m.height} layers high. No gaps.`).join(' '):'The object drawings show their visible faces and surfaces. Some faces, edges and vertices may be hidden behind.'} label="Read diagram" className={shared.voice}/></div>{choices(s.options!)}</div>:choices(s.options!)}
   {s.reasons&&<div className={shared.reasonSection}><h3>Why?</h3>{choices(s.reasons,true)}</div>}
  </>}</>;
 }
 const l=item.task;
 if(l.mode==='views')return <>{header}<RoomViews variant={l.viewVariant!}/><ReadAloudBtn text={`Plan view, from above: the table is on the ${l.viewVariant!%2?'right':'left'} inside the room with chairs around it and a doorway at the bottom. Front view, from outside: the wall has a ${l.viewVariant!%3===1?'flat':'triangular'} roof, a tall doorway and two windows. Furniture inside is not shown.`} label="Read views" className={shared.voice}/><div className={styles.viewAnswers}>{choices(l.options!)}</div></>;
 const mapped=l.mode==='build'?l.landmarks.filter(p=>a.placements[p.id]).map(p=>({...p,cell:a.placements[p.id]})):l.landmarks;
 const select=active??l.landmarks[0].id;
 return <>{header}<div className={styles.split}><div className={styles.mapPanel}><h3 className={styles.builderTitle}>{l.title} · view from above</h3><div className={styles.mapGrid}>{Array.from({length:16},(_,i)=>{const c={r:Math.floor(i/4),c:i%4},landmark=mapped.find(p=>sameCell(p.cell,c)),explorer=l.explorer&&sameCell(c,l.explorer.cell),inside=<>{landmark&&<><Symbol landmark={landmark}/><span>{landmark.label}</span></>}{explorer&&<><b className={styles.facing}>{ARROWS[l.explorer!.facing]}</b><span>Explorer</span></>}</>;return l.mode==='build'?<button key={i} className={styles.cell} aria-label={`Map square row ${c.r+1}, column ${c.c+1}`} onClick={()=>{const placements={...a.placements};for(const [id,p]of Object.entries(placements))if(sameCell(p,c))delete placements[id];placements[select]=c;onChange({...a,placements});}}>{inside}</button>:<div key={i} className={styles.cell}>{inside}</div>;})}</div><ReadAloudBtn text={`Rows are counted from the top, columns from the left. ${mapped.map(p=>`${p.label}: row ${p.cell.r+1}, column ${p.cell.c+1}.`).join(' ')} ${l.explorer?`Explorer: row ${l.explorer.cell.r+1}, column ${l.explorer.cell.c+1}, facing ${l.explorer.facing}.`:''}`} label="Read map" className={shared.voice}/></div><div>{l.mode==='build'?<><ol className={styles.clues}>{l.constraints!.map((c,i)=><li key={i}>{constraintText(l,c)}</li>)}</ol><ReadAloudBtn text={l.constraints!.map(c=>constraintText(l,c)).join(' ')} label="Read clues" className={shared.voice}/><div className={styles.palette}>{l.landmarks.map(p=><button key={p.id} data-landmark-id={p.id} aria-pressed={p.id===select} onClick={()=>setActive(p.id)}><Symbol landmark={p}/>{p.label}</button>)}</div><ReadAloudBtn text={`Choose a landmark: ${l.landmarks.map(p=>p.label).join(', ')}. Then tap its square. Placing on an occupied square replaces that landmark. Clear removes all landmarks.`} label="Read controls" className={shared.voice}/><div className={shared.tools}><button onClick={()=>onChange({...a,placements:{}})} disabled={!Object.keys(a.placements).length}>Clear</button></div></>:choices(l.options!)}</div></div></>;
}
