import type {Cell,Direction} from '@/data/assessments/revisions/level1StarpathFiveForms';
import {routeCells} from '@/data/assessments/revisions/level1StarpathFiveForms';
import {type Level4Item,type SymTask,type SymCell,gridRef,symTransform,symKey} from '@/data/assessments/revisions/level4StarpathFiveForms';
import {normaliseGridReference} from './starpath-grid-reference';
import {sameCell} from './starpath-level1-review';
export type Level4Response={selected:string[];heights:number[];reference:string;cell:Cell|null;placements:Record<string,Cell>;labels:Record<string,string>;moves:Direction[];tiles:SymCell[]};
export const emptyLevel4Response=(item:Level4Item):Level4Response=>({selected:[],heights:item.kind==='composite'&&item.task.model?item.task.model.heights.map(()=>0):[],reference:'',cell:null,placements:{},labels:{},moves:[],tiles:item.kind==='symmetry'?[...item.task.seeds]:[]});
export function level4ResponseReady(item:Level4Item,a:Level4Response){const t=item.task;if(item.kind==='composite')return item.task.model?a.heights.some(h=>h>0):a.selected.length>0;if(item.kind==='symmetry')return t.mode==='choice'?a.selected.length>0:a.tiles.length>item.task.seeds.length;if(item.kind==='grid'){switch(item.task.mode){case 'reference':return a.reference.trim().length>0;case 'locate':return a.cell!==null;case 'place':return item.task.landmarks.every(l=>a.placements[l.id]);case 'labels':return ['c0','c1','c2','c3','r0','r1','r2','r3'].every(k=>a.labels[k]?.trim());case 'route':return a.moves.length>0;default:return a.selected.length>0;}}return false;}
export function symmetric(t:SymTask,tiles:SymCell[]){const palette=new Set(t.expected.map(c=>c.colour)),map=new Map(tiles.map(c=>[symKey(c),c.colour]));return tiles.length===map.size&&tiles.every(c=>Number.isInteger(c.r)&&Number.isInteger(c.c)&&c.r>=0&&c.r<5&&c.c>=0&&c.c<5&&palette.has(c.colour)&&map.get(symKey(symTransform(t,c)))===c.colour);}
export function scoreLevel4Response(item:Level4Item,a:Level4Response){
 if(item.kind==='composite'){const t=item.task;if(t.model)return a.heights.length===t.model.heights.length&&a.heights.every((h,i)=>h===t.model!.heights[i]);return !!t.correctIds&&a.selected.length===t.correctIds.length&&new Set(a.selected).size===a.selected.length&&t.correctIds.every(id=>a.selected.includes(id));}
 if(item.kind==='symmetry'){const t=item.task;if(t.mode==='choice')return a.selected.length===1&&a.selected[0]===t.correctId;if(t.mode==='create')return a.tiles.length>=t.minCells!&&new Set(a.tiles.map(c=>c.colour)).size===2&&symmetric(t,a.tiles);return a.tiles.length===t.expected.length&&new Set(a.tiles.map(symKey)).size===a.tiles.length&&t.expected.every(c=>a.tiles.some(p=>sameCell(c,p)&&p.colour===c.colour));}
 const t=item.task;
 if(t.mode==='choice')return a.selected.length===1&&a.selected[0]===t.correctId;
 if(t.mode==='reference')return normaliseGridReference(a.reference)===gridRef(t,t.target!);
 if(t.mode==='locate')return !!a.cell&&sameCell(a.cell,t.target!);
 if(t.mode==='place')return Object.entries(t.placements!).every(([id,c])=>!!a.placements[id]&&sameCell(c,a.placements[id]));
 if(t.mode==='labels')return t.columnLabels.every((v,i)=>normaliseGridReference(a.labels[`c${i}`]??'')===v)&&t.rowLabels.every((v,i)=>normaliseGridReference(a.labels[`r${i}`]??'')===v);
 const path=routeCells(t.start!,a.moves),arrival=path.findIndex(c=>sameCell(c,t.goal!));return a.moves.length>0&&path.every(c=>c.r>=0&&c.r<4&&c.c>=0&&c.c<4&&!t.blocked.some(b=>sameCell(c,b)))&&arrival===path.length-1&&(!t.checkpoint||path.slice(0,arrival).some(c=>sameCell(c,t.checkpoint!)));
}
export function level4Expected(item:Level4Item){if(item.kind==='composite'){const t=item.task;return t.model?`Column heights: ${t.model.heights.join(', ')}.`:t.options!.filter(o=>t.correctIds!.includes(o.id)).map(o=>o.label).join('; ');}if(item.kind==='symmetry'){const t=item.task;return t.mode==='choice'?t.options!.find(o=>o.id===t.correctId)!.label:t.mode==='create'?'Any design with at least six tiles, both colours and the stated symmetry.':`Matching tiles at ${t.expected.map(c=>`row ${c.r+1}, column ${c.c+1}`).join('; ')}; colours must match.`;}const t=item.task;return t.mode==='choice'?t.options!.find(o=>o.id===t.correctId)!.label:t.mode==='labels'?'Columns A, B, C, D; rows 4, 3, 2, 1 from top to bottom.':t.mode==='route'?`Any valid route. Example: ${t.example!.join(', ')}.`:t.mode==='place'?t.landmarks.map(l=>`${l.label}: ${gridRef(t,t.placements![l.id])}`).join('; '):gridRef(t,t.target!);}
