import type {GroundRedesignItem} from '@/data/assessments/revisions/groundStarpathRedesignedForms';
import {emptyGroundResponse,groundResponseReady,scoreGroundResponse,type GroundResponse} from './starpath-ground-redesign';
import type {Level1Item} from '@/data/assessments/revisions/level1StarpathFiveForms';
import {emptyLevel1Response,level1ResponseReady,scoreLevel1Response,level1Expected,type Level1Response} from './starpath-level1-review';
import type {Level2Item} from '@/data/assessments/revisions/level2StarpathFiveForms';
import {emptyLevel2Response,level2ResponseReady,scoreLevel2Response,level2Expected,type Level2Response} from './starpath-level2-review';
import type {Level3Item} from '@/data/assessments/revisions/level3StarpathFiveForms';
import {emptyLevel3Response,level3ResponseReady,scoreLevel3Response,level3Expected,type Level3Response} from './starpath-level3-review';
import type {Level4Item} from '@/data/assessments/revisions/level4StarpathFiveForms';
import {emptyLevel4Response,level4ResponseReady,scoreLevel4Response,level4Expected,type Level4Response} from './starpath-level4-review';
import type {Level5Item} from '@/data/assessments/revisions/level5StarpathFiveForms';
import {emptyLevel5Response,level5ResponseReady,scoreLevel5Response,level5Expected,type Level5Response} from './starpath-level5-review';
import type {Level6Item} from '@/data/assessments/revisions/level6StarpathFiveForms';
import {emptyLevel6Response,level6ResponseReady,scoreLevel6Response,level6Expected,type Level6Response} from './starpath-level6-review';
import type {Level7Item} from '@/data/assessments/revisions/level7StarpathFiveForms';
import {emptyLevel7Response,level7ResponseReady,scoreLevel7Response,level7Expected,type Level7Response} from './starpath-level7-review';
import type {Level8Item} from '@/data/assessments/revisions/level8StarpathFiveForms';
import {emptyLevel8Response,level8ResponseReady,scoreLevel8Response,level8Expected,type Level8Response} from './starpath-level8-review';
export type StarpathReleaseVisual={type:'starpath_released';level:0;item:GroundRedesignItem}|{type:'starpath_released';level:1;item:Level1Item}|{type:'starpath_released';level:2;item:Level2Item}|{type:'starpath_released';level:3;item:Level3Item}|{type:'starpath_released';level:4;item:Level4Item}|{type:'starpath_released';level:5;item:Level5Item}|{type:'starpath_released';level:6;item:Level6Item}|{type:'starpath_released';level:7;item:Level7Item}|{type:'starpath_released';level:8;item:Level8Item};
export function starpathReleaseVisual(q:{visual?:unknown}):StarpathReleaseVisual|null{const v=q.visual as StarpathReleaseVisual|undefined;return v?.type==='starpath_released'&&Number.isInteger(v.level)&&v.level>=0&&v.level<=8&&!!v.item?v:null;}
export function initialStarpathResponse(v:StarpathReleaseVisual):unknown{switch(v.level){case 0:return emptyGroundResponse(v.item.task);case 1:return emptyLevel1Response(v.item);case 2:return emptyLevel2Response(v.item);case 3:return emptyLevel3Response(v.item);case 4:return emptyLevel4Response(v.item);case 5:return emptyLevel5Response(v.item);case 6:return emptyLevel6Response(v.item);case 7:return emptyLevel7Response(v.item);case 8:return emptyLevel8Response(v.item);}}
const PREFIX='__starpath_release_v1__:';
export function encodeReleasedStarpath(id:string,response:unknown){return PREFIX+JSON.stringify({questionId:id,response});}
export function readReleasedStarpath(id:string,value:unknown):unknown{if(typeof value!=='string'||!value.startsWith(PREFIX))return null;try{const v=JSON.parse(value.slice(PREFIX.length));return v.questionId===id&&v.response&&typeof v.response==='object'?v.response:null;}catch{return null;}}
export function readyReleasedStarpath(q:{id?:string;visual?:unknown},value:unknown):boolean{if(value==="idk" || value==="__unknown__")return true;const v=starpathReleaseVisual(q),r=readReleasedStarpath(q.id??'',value);if(!v||!r)return false;try{switch(v.level){case 0:return groundResponseReady(v.item.task,r as GroundResponse);case 1:return level1ResponseReady(v.item,r as Level1Response);case 2:return level2ResponseReady(v.item,r as Level2Response);case 3:return level3ResponseReady(v.item,r as Level3Response);case 4:return level4ResponseReady(v.item,r as Level4Response);case 5:return level5ResponseReady(v.item,r as Level5Response);case 6:return level6ResponseReady(v.item,r as Level6Response);case 7:return level7ResponseReady(v.item,r as Level7Response);case 8:return level8ResponseReady(v.item,r as Level8Response);}}catch{return false;}}
export function scoreReleasedStarpath(q:{id?:string;visual?:unknown},value:unknown):boolean{const v=starpathReleaseVisual(q),r=readReleasedStarpath(q.id??'',value);if(!v||!r)return false;try{switch(v.level){case 0:return scoreGroundResponse(v.item.task,r as GroundResponse);case 1:return scoreLevel1Response(v.item,r as Level1Response);case 2:return scoreLevel2Response(v.item,r as Level2Response);case 3:return scoreLevel3Response(v.item,r as Level3Response);case 4:return scoreLevel4Response(v.item,r as Level4Response);case 5:return scoreLevel5Response(v.item,r as Level5Response);case 6:return scoreLevel6Response(v.item,r as Level6Response);case 7:return scoreLevel7Response(v.item,r as Level7Response);case 8:return scoreLevel8Response(v.item,r as Level8Response);}}catch{return false;}}
export function expectedReleasedStarpath(v:StarpathReleaseVisual):string{switch(v.level){case 0:{const t=v.item.task;return t.mode==='draw'?`Any valid ${t.drawShape}.`:t.mode==='compose'?'Two pieces joined into a square.':t.mode==='place'?`Any space ${t.relation} the reference object.`:(t.options??[]).filter(o=>t.correctIds?.includes(o.id)).map(o=>o.label??o.id).join('; ')+(t.correctReason?' — '+t.reasons?.find(r=>r.id===t.correctReason)?.label:'');}case 1:return level1Expected(v.item);case 2:return level2Expected(v.item);case 3:return level3Expected(v.item);case 4:return level4Expected(v.item);case 5:return level5Expected(v.item);case 6:return level6Expected(v.item);case 7:return level7Expected(v.item);case 8:return level8Expected(v.item);}}
