'use client';
import ObjectArt from './StatisticaObjectArt';
import SeedlingTray from './StatisticaSeedlingTray';
import StatisticaSortActivity from './StatisticaSortActivity';
import ReviewGraph from './StatisticaReviewGraph';
import ReviewLineGraph from './StatisticaReviewLineGraph';
import Pictograph,{pictographSpeech} from './StatisticaReviewPictograph';
import ReadAloudBtn from '@/components/ReadAloudBtn';
import type {StatsItem,Category} from '@/data/assessments/revisions/level1StatisticaFiveForms';
import type {StatsResponse} from '@/lib/statistica-level1-review';
import styles from '@/components/demo/StatisticaFiveForms.module.css';

function Marks({n,display,category}:{n:number;display:StatsItem['display'];category:Category}){
 if(display==='tally')return <div className={styles.marks} aria-label={`${n} tally marks`}>{Array.from({length:Math.ceil(n/5)},(_,g)=><svg key={g} viewBox="0 0 40 38" width="40" height="38" aria-hidden="true">{Array.from({length:Math.min(4,n-g*5)},(_,i)=><path key={i} d={`M${6+i*8} 5V33`} stroke="currentColor" strokeWidth="2.5"/>)}{n-g*5>=5&&<path d="M2 31L37 7" stroke="currentColor" strokeWidth="2.5"/>}</svg>)}</div>;
 return <div className={styles.marks} aria-label={`${n} ${display==='pictures'?category.name:'marks'}`}>{Array.from({length:n},(_,i)=><span className={styles.unit} key={i} aria-hidden="true">{display==='pictures'?<ObjectArt name={category.name} color={category.color} size={32}/>:<span className={display==='objects'?styles.counterDisc:styles.dot}/>}</span>)}{n===0&&<span className={styles.zero}>0</span>}</div>;
}
export default function StatisticaAssessmentCard({item,response,onChange}:{item:StatsItem;response:StatsResponse;onChange:(r:StatsResponse)=>void}){
 const names=item.categories.map(c=>c.name);
 const observationLabel=item.sourceLabel??(item.source==='objects'?'Picture':'Child');
 const countSpeech=item.counts.map((n,i)=>`${names[i]}: ${n}`).join('. ');
 const graphProps={max:item.graphMax??12,step:item.graphStep??1,minorStep:item.graphMinorStep,axisLabel:item.axisLabel,valueLabel:item.valueLabel,numerical:item.numerical};
 const scaleSpeech=`Scale from zero to ${graphProps.max} in steps of ${graphProps.step}.${item.graphMinorStep?` Smaller marks show steps of ${item.graphMinorStep}.`:""} ${item.valueLabel??'Groups'} on the bottom axis.`;
 const art=(i:number,size:number)=>item.observationArt==='seedlings'?<SeedlingTray count={Number(names[i])}/>:item.numerical?<span className={styles.numericValue}>{names[i]}</span>:item.plainCategories?null:<ObjectArt name={names[i]} color={item.categories[i].color} size={size}/>;
 const sourceSpeech=item.source==='line'?`${item.context}. ${scaleSpeech} ${item.linePoints?.map(p=>`${p.label}: ${p.value}`).join('. ')}.`:item.source==='records'?`${item.context}. ${item.observations.map((v,i)=>`Record ${i+1}, participant ${item.recordIds?.[i]}: ${names[v]}`).join('. ')}.`:item.source==='pictograph'?`${item.context}. ${pictographSpeech(item.categories,item.counts,item.keyUnits??1)} ${item.allowHalf?`Half a picture represents ${item.keyUnits!/2}.`:''}`:item.source==='comparison'?`${item.context}. ${scaleSpeech} Group A: ${countSpeech}. Group B: ${item.secondCounts?.map((n,i)=>`${names[i]}: ${n}`).join('. ')}.`:item.source==='brief'?`${item.context}. ${item.sourceText}`:item.source==='dual'?`${item.context}. Graph A uses ${item.numerical?'dots':'pictures'}. One ${item.numerical?'dot represents one child':'picture represents one answer'}. ${countSpeech}. Graph B uses columns, ${scaleSpeech} ${ (item.secondaryOrder??item.categories.map((_,i)=>i)).map(i=>`${names[i]}: ${item.counts[i]}`).join('. ')}.`:item.source==='table'?`${item.context}. Frequency table. Frequency means how many were recorded. ${countSpeech}.`:item.source==='categories'?`Possible answers: ${names.join(', ')}.`:item.source==='graph'?`${item.context}. ${item.graphKind==='columns'?`Column graph. ${scaleSpeech}`:'One picture stands for one answer.'} ${countSpeech}.`:`${item.context}. ${item.observations.map((v,i)=>`${observationLabel} ${i+1}: ${names[v]}`).join('. ')}.`;
 const listSpeech=item.source==='missing'?`Recorded list: ${item.recorded?.map((v,i)=>`Child ${i+1}: ${names[v]}`).join('. ')}.`:item.source==='duplicate'?`Recorded list: ${item.recorded?.map(i=>`Child ${i+1}: ${names[item.observations[i]]}`).join('. ')}.`:'';
 const limit=item.responseMax??(item.display==='columns'?12:20);
 const setValue=(i:number,n:number)=>onChange({...response,touched:true,values:response.values.map((v,j)=>i===j?Math.max(0,Math.min(limit,n)):v)});
 const controls=(n:number,i:number)=>{const c=item.categories[item.target??i],factor=item.display==='pictograph'?(item.keyUnits??1):1,step=item.display==='pictograph'?factor:item.responseStep??1;return <div className={styles.adjust}><button aria-label={`Remove ${item.responseMax===undefined?'one':item.display==='pictograph'?'one picture':step} from ${c.name}`} disabled={n===0} onClick={()=>setValue(i,n-step)}>−</button>{item.responseMax!==undefined?<input className={styles.frequencyInput} aria-label={`${c.name} ${item.display==='pictograph'?'pictures':'frequency'}`} type="number" min="0" max={limit/factor} step={step/factor} value={n/factor} onFocus={e=>e.currentTarget.select()} onBlur={e=>{e.currentTarget.value=String(n/factor);}} onChange={e=>{const value=Number(e.target.value);if(Number.isFinite(value)&&Number.isInteger(value))setValue(i,value*factor);}}/>:<output aria-label={`${c.name} recorded`}>{n}</output>}<button aria-label={`Add ${item.responseMax===undefined?'one':item.display==='pictograph'?'one picture':step} to ${c.name}`} disabled={n>=limit} onClick={()=>setValue(i,n+step)}>+</button></div>;};
 const table=(values:number[],editable=false)=><table className={styles.frequencyTable}><thead><tr><th scope="col">{item.valueLabel??'Group'}</th><th scope="col">Frequency</th></tr></thead><tbody>{values.map((n,i)=><tr key={i}><th scope="row"><span className={styles.category}>{item.numerical?names[i]:<>{art(i,34)}{names[i]}</>}</span></th><td>{editable?controls(n,i):n}</td></tr>)}</tbody></table>;
 const graph=(values:number[],editable=false)=>{
  if((editable&&item.display==='pictograph')||(!editable&&item.source==='pictograph'))return <><Pictograph categories={item.categories} values={values} keyUnits={item.keyUnits??1} symbolName={item.symbolName??'Ball'} unitNoun={item.axisLabel?.toLowerCase()} allowHalf={item.allowHalf}/>{editable&&<div className={styles.columnControls}>{values.map((n,i)=><div key={i}><strong>{names[i]} · pictures</strong>{controls(n,i)}</div>)}</div>}</>;
  if(editable&&item.display==='frequency')return table(values,true);
  if(editable&&item.display==='columns')return <><ReviewGraph {...graphProps} categories={item.categories} values={values} kind="columns"/><div className={styles.columnControls}>{values.map((n,i)=><div key={i}><strong>{names[i]}</strong>{controls(n,i)}</div>)}</div></>;
  if(!editable&&item.graphKind==='columns')return <ReviewGraph {...graphProps} categories={item.categories} values={values} kind="columns"/>;
  return <div className={styles.graph}>{values.map((n,i)=>{const c=item.categories[editable?(item.target??i):i];return <div className={styles.graphRow} key={i}><span className={styles.category} data-category={c.name}><ObjectArt name={c.name} color={c.color} size={30}/>{c.name}</span><Marks n={n} display={editable?item.display:'pictures'} category={c}/>{editable&&controls(n,i)}</div>;})}</div>;
 };
 return <>
  <div className={styles.question}><h2 id="stats-question-heading">{item.prompt}</h2><ReadAloudBtn className={styles.voice} label="Read question" text={`${item.prompt} ${item.instruction}`}/></div>
  {item.instruction&&<p className={styles.instruction}>{item.instruction}</p>}
  {item.mode==='sort'?<StatisticaSortActivity item={item} response={response} onChange={onChange}/>:<div className={`${styles.activity} ${(item.source==='dual'||item.source==='comparison')?styles.wideActivity:''}`}>
   <div className={styles.source} data-stats-source><div className={styles.panelHeader}><h3>{item.source==='categories'?'Survey answers':item.context}</h3><ReadAloudBtn className={styles.voice} label="Read diagram" text={`${sourceSpeech} ${listSpeech}`}/></div>
    {item.source==='line'?<ReviewLineGraph points={item.linePoints!} max={graphProps.max} step={graphProps.step} unit={item.axisLabel??'Number'}/>:item.source==='records'?<table className={styles.frequencyTable}><thead><tr><th>Record</th><th>Participant</th><th>Response</th></tr></thead><tbody>{item.observations.map((v,i)=><tr key={i} data-record-index={i+1}><th scope="row">{i+1}</th><td>{item.recordIds?.[i]}</td><td>{names[v]}</td></tr>)}</tbody></table>:item.source==='comparison'?<div className={styles.twoGraphs}>{[item.counts,item.secondCounts!].map((values,i)=><div key={i}><h4>Group {i===0?'A':'B'}</h4><ReviewGraph {...graphProps} categories={item.categories} values={values} kind="columns"/></div>)}</div>:item.source==='pictograph'?graph(item.counts):item.source==='brief'?<p className={styles.sourceBrief}>{item.sourceText}</p>:item.source==='dual'?<div className={styles.twoGraphs}><div><h4>Graph A · {item.numerical?'Dots':'Pictures'}</h4><ReviewGraph {...graphProps} categories={item.categories} values={item.counts} kind="pictures"/></div><div><h4>Graph B · Columns</h4><ReviewGraph {...graphProps} categories={item.categories} values={item.counts} kind="columns" order={item.secondaryOrder}/></div></div>:item.source==='table'?table(item.counts):item.source==='graph'?graph(item.counts):item.source==='categories'?<div className={styles.categoryChoices}>{item.categories.map(c=><div key={c.name}><ObjectArt name={c.name} color={c.color} size={80}/><span>{c.name}</span></div>)}</div>:<div className={styles.observations}>{item.observations.map((v,i)=><div key={i}><span>{observationLabel} {i+1}</span>{art(v,58)}{!item.numerical&&<strong>{names[v]}</strong>}</div>)}</div>}
    {(item.source==='missing'||item.source==='duplicate')&&<div className={styles.recordList}><h4>Recorded list</h4>{item.recorded?.map((v,i)=>{const child=item.source==='duplicate'?v:i;const cat=item.source==='duplicate'?item.observations[v]:v;return <span key={i}>Child {child+1}: {names[cat]}</span>;})}</div>}
   </div>
   <div className={`${styles.answer} ${(item.source==='dual'||item.source==='comparison')?styles.wideOptions:''}`}>
    {item.mode==='choice'?item.options.map(o=><div className={styles.option} key={o.id}><button aria-pressed={response.choice===o.id} onClick={()=>onChange({...response,choice:o.id,touched:true})}>{o.label}</button><ReadAloudBtn className={styles.voice} kind="option" text={o.label}/></div>):item.mode==='counts'?<><div className={styles.panelHeader}><h3>Your {item.display==='tally'?'tally':item.display==='frequency'?'frequency table':item.display==='columns'?'column graph':'display'}</h3><ReadAloudBtn className={styles.voice} label="Read display" text={`Your display.${item.display==='pictograph'?` Key: one picture represents ${item.keyUnits} ${item.axisLabel?.toLowerCase()??'items'}.`:""} ${response.values.map((n,i)=>`${names[item.target??i]}: ${item.display==='pictograph'?`${n/(item.keyUnits??1)} pictures`:n}`).join('. ')}. ${item.responseMax!==undefined?`Type a value, or use plus and minus to change it by ${item.display==='pictograph'?'one picture':item.responseStep??1}.`:'Use plus to add one, minus to remove one.'}${item.display==='columns'?` ${scaleSpeech}`:''}`}/></div>{graph(response.values,true)}</>:<><div className={styles.panelHeader}><h3>Your list</h3><ReadAloudBtn className={styles.voice} label="Read list" text={`${item.instruction} ${response.values.map((v,i)=>`${observationLabel} ${i+1}: ${v<0?'not chosen':names[v]}`).join('. ')}. Choices: ${names.join(', ')}.`}/></div><div className={styles.entries}>{response.values.map((v,i)=><label key={i}>{observationLabel} {i+1}<select aria-label={`${observationLabel} ${i+1} answer`} value={v} onChange={e=>onChange({...response,touched:true,values:response.values.map((old,j)=>j===i?Number(e.target.value):old)})}><option value={-1}>Choose…</option>{names.map((name,k)=><option key={name} value={k}>{name}</option>)}</select></label>)}</div></>}
   </div>
  </div>}
 </>;
}
