'use client';
import {useState} from 'react';
import ReadAloudBtn from '@/components/ReadAloudBtn';
import {getRealmTheme} from '@/lib/useRealmTheme';
import Cave7Visual from './Cave7Visual';
import type {NewCave7Realm} from '@/data/activities/cave7/curriculum';
const button='rounded-lg border border-current px-4 py-2 font-bold focus-visible:outline-2 focus-visible:outline-offset-2';
export default function Cave7LearningLab({realm,week}:{realm:NewCave7Realm;week:number}){
 const t=getRealmTheme(realm),[inputs,setInputs]=useState([3,4,2]),[rows,setRows]=useState<number[][]>([]),[trials,setTrials]=useState(0),[wins,setWins]=useState(0),[entries,setEntries]=useState('21, 24, 24, 29, 32, 35, 38, 41'),[leaves,setLeaves]=useState(['','','']),[dots,setDots]=useState([0,0,0,0]),[feedback,setFeedback]=useState('');
 const [pointX,setPointX]=useState(1),[pointY,setPointY]=useState(0),[points,setPoints]=useState<[number,number][]>([]);
 const title=realm==='chance'?'Run a real experiment':realm==='pattern'?(week===10?'Build a function graph':'Explore a formula'):week===6?'Construct a stem-and-leaf plot':week===7?'Build a dot plot':'Investigate your data';
 function run(count:number){let total=0;for(let i=0;i<count;i++)if(Math.random()<.3)total++;setTrials(n=>n+count);setWins(n=>n+total);setFeedback(`This run: ${total} red results from ${count} spins.`);}
 function summarise(){const parts=entries.split(',').map(s=>s.trim());if(parts.some(s=>!s||!Number.isFinite(Number(s)))){setFeedback('Enter comma-separated numbers.');return;}const data=parts.map(Number).sort((a,b)=>a-b),mid=Math.floor(data.length/2),median=data.length%2?data[mid]:(data[mid-1]+data[mid])/2;setFeedback(`Count ${data.length}. Mean ${Number((data.reduce((s,n)=>s+n,0)/data.length).toFixed(3))}. Median ${median}. Range ${Number((data.at(-1)!-data[0]).toFixed(3))}. Describe what changes when you add an extreme value.`);}
 return <details className="mt-5 rounded-xl border bg-white p-4 text-slate-900" style={{borderColor:t.ctaFrom}}><summary className="cursor-pointer text-lg font-bold">Try it yourself · {title}</summary><div className="mt-4">
 <div className="mb-4 flex justify-between gap-3"><p>This exploration is untimed. Test a change, observe the result and explain it.</p><ReadAloudBtn text={`${title}. This exploration is untimed. Test a change, observe the result and explain it.`}/></div>
 {realm==='chance'?<><Cave7Visual realm={realm} visual={{kind:'chance',title:'Probability model: red = 3/10',apparatus:{type:'spinner',wedges:['#e5484d','#e5484d','#e5484d',...Array(7).fill('#3b82f6')]},caption:'Ten equal sections: three red and seven blue. Independent trials use this same probability.'}}/><div className="flex flex-wrap gap-3">{[10,100,1000].map(n=><button className={button} key={n} onClick={()=>run(n)}>Run {n} trials</button>)}<button className={button} onClick={()=>{setTrials(0);setWins(0);setFeedback('Experiment reset.');}}>Reset</button></div><p className="mt-3">Actual results: {wins} red / {trials} trials. Observed share: {trials?(wins/trials).toFixed(3):'—'}. Expected count: {(trials*.3).toFixed(1)}.</p><ReadAloudBtn text={`Actual results: ${wins} red in ${trials} trials. Observed share ${trials?(wins/trials).toFixed(3):'not yet available'}. Expected count ${trials*.3}.`} label="Read results"/></>:
 realm==='pattern'&&week===10?<><p>Build points for y = 2x + 1. Enter a point, then check and add it.</p><ReadAloudBtn text="Build points for y equals two x plus one. Enter x and y, then check and add the point."/><div className="my-3 flex flex-wrap gap-3">{[['x',pointX,setPointX],['y',pointY,setPointY]].map(([name,value,setter])=><label key={String(name)}>{String(name)} <input aria-label={`Coordinate ${name}`} type="number" min="0" max="15" className="w-20 rounded border p-2" value={value as number} onChange={e=>(setter as (n:number)=>void)(Number(e.target.value))}/></label>)}<button className={button} onClick={()=>{if(pointX<0||pointX>6||!Number.isInteger(pointX)||pointY!==2*pointX+1){setFeedback('Use a whole-number x from 0 to 6. Calculate 2 × x + 1 for y, then try again.');return;}setPoints(ps=>[...ps.filter(p=>p[0]!==pointX),[pointX,pointY] as [number,number]].sort((a,b)=>a[0]-b[0]));setFeedback('Point added. Try another input and look for the relationship.');}}>Check and add</button></div>{points.length>0&&<Cave7Visual realm={realm} visual={{kind:'plot',title:'Your function graph',xLabel:'x',yLabel:'y',points,connect:false}}/>}</>:
 realm==='pattern'?<><p>V = l × w × h. Keep one input fixed while changing another. Record the results and explain how volume changes.</p><ReadAloudBtn text="Volume equals length times width times height. Keep one input fixed while changing another. Record the results and explain how volume changes."/><div className="my-3 flex flex-wrap gap-3">{['Length','Width','Height'].map((name,i)=><label key={name}>{name} (cm) <input aria-label={`${name} in centimetres`} type="number" min="1" max="20" className="w-20 rounded border p-2" value={inputs[i]} onChange={e=>setInputs(xs=>xs.map((x,j)=>i===j?Math.max(1,Math.min(20,Number(e.target.value)||1)):x))}/></label>)}<button className={button} onClick={()=>setRows(rs=>[...rs.slice(-9),[...inputs,inputs.reduce((p,n)=>p*n,1)]])}>Calculate and record</button></div>{rows.length>0&&<Cave7Visual realm={realm} visual={{kind:'table',title:'Your formula investigation',headers:['l (cm)','w (cm)','h (cm)','V (cm³)'],rows:rows.map(r=>r.map(String))}}/>}</>:
 week===6?<><p>Construct ordered leaves for 21, 24, 24, 29, 32, 35, 38, 41. Key: 2 | 1 means 21.</p><ReadAloudBtn text="Construct ordered leaves for 21, 24, 24, 29, 32, 35, 38, 41. Key: stem 2, leaf 1 means 21. Keep repeated leaves."/>{[2,3,4].map((s,i)=><label className="my-2 flex gap-3" key={s}>Stem {s}<input aria-label={`Leaves for stem ${s}`} className="rounded border p-2" placeholder="Leaves in order" value={leaves[i]} onChange={e=>setLeaves(xs=>xs.map((x,j)=>i===j?e.target.value:x))}/></label>)}<button className={button} onClick={()=>setFeedback(leaves.every((s,i)=>s.trim().split(/[ ,]+/).join(' ')===['1 4 4 9','2 5 8','1'][i])?'Correct. Every observation is represented, including both 24s.':'Check tens and units, keep both 24s, and put leaves in ascending order.')}>Check construction</button></>:
 week===7?<><p>Build a dot plot for 1, 2, 2, 3, 3, 3, 4. Set each frequency.</p><ReadAloudBtn text="Build a dot plot for 1, 2, 2, 3, 3, 3, 4. Set the frequency for each value, then check."/><div className="flex flex-wrap gap-3">{dots.map((n,i)=><label key={i}>Value {i+1}<input aria-label={`Frequency for value ${i+1}`} className="ml-2 w-16 rounded border p-2" type="number" min="0" max="7" value={n} onChange={e=>setDots(xs=>xs.map((x,j)=>i===j?Math.max(0,Math.min(7,Number(e.target.value))):x))}/></label>)}</div><div className="my-4 flex justify-around">{dots.map((n,i)=><div key={i} className="flex min-h-24 flex-col justify-end text-center"><span>{Array.from({length:n},(_,j)=><span className="block" key={j}>●</span>)}</span><strong>{i+1}</strong></div>)}</div><ReadAloudBtn text={dots.map((n,i)=>`Value ${i+1}, ${n} dots`).join('. ')} label="Read your plot"/><button className={button} onClick={()=>setFeedback(dots.every((n,i)=>n===[1,2,3,1][i])?'Correct: all seven observations are represented.':'Count each repeated value again; every observation needs a dot.')}>Check construction</button></>:
 <><label className="block">Your observations, separated by commas<textarea className="mt-2 w-full rounded border p-3" value={entries} onChange={e=>setEntries(e.target.value)}/></label><button className={button} onClick={summarise}>Calculate summaries</button><p className="mt-2 text-sm">Try a second data set or add an extreme value, then compare the results.</p></>}
 {feedback&&<div className="mt-4 flex items-start justify-between gap-3 rounded-lg bg-slate-100 p-3"><p aria-live="polite">{feedback}</p><ReadAloudBtn text={feedback}/></div>}
 </div></details>;
}
