'use client';
import ReadAloudBtn from '@/components/ReadAloudBtn';
import ChanceVisual from '@/components/chance-hollow/ChanceVisual';
import {getRealmTheme} from '@/lib/useRealmTheme';
import type {Cave7Visual as Visual} from '@/data/activities/cave7/shared';
export function cave7VisualSpeech(v:Visual){return [v.title,v.kind==='table'?`${v.headers.join('; ')}. ${v.rows.map(row=>row.join('; ')).join('. ')}. ${v.caption??''}`:v.kind==='formula'?`${v.formula}. ${v.meaning}`:v.kind==='chance'?v.caption:v.kind==='pattern'?Array.from({length:v.stages},(_,i)=>`Stage ${i+1} has ${v.fixed+v.group*(i+1)} ${v.unit}`).join('. ')+`. Each stage shows ${v.fixed} ${v.unit} in a separate column, then one column of ${v.group} ${v.unit} for each stage number.`:v.kind==='balance'?`A balanced scale. Left pan: ${v.left}. Right pan: ${v.right}.`:v.kind==='frequency'?`${v.unit}. ${v.values.map((n,i)=>`Value ${n}: frequency ${v.counts[i]}`).join('. ')}`:`Horizontal axis: ${v.xLabel}. Vertical axis: ${v.yLabel}${v.yStep?`, gridlines every ${v.yStep}`:''}. ${v.points.map(p=>`Point ${p[0]}, ${p[1]}`).join('. ')}. ${v.connect?'Recorded points are joined.':'Points are not joined.'}`].join('. ');}
export default function Cave7Visual({visual:v,realm}:{visual:Visual;realm:string}){
 const t=getRealmTheme(realm);let body;
 if(v.kind==='table')body=<div className="overflow-x-auto"><table className="w-full text-left text-base"><thead><tr>{v.headers.map(h=><th key={h} className="border-b p-3">{h}</th>)}</tr></thead><tbody>{v.rows.map((row,i)=><tr key={i}>{row.map((s,j)=><td key={j} className="border-b border-slate-200 p-3">{s}</td>)}</tr>)}</tbody></table>{v.caption&&<p className="mt-2">{v.caption}</p>}</div>;
 else if(v.kind==='formula')body=<><p className="py-4 text-center text-2xl font-bold sm:text-3xl">{v.formula}</p><p className="text-center">{v.meaning}</p></>;
 else if(v.kind==='pattern'){
  // Fixed tiles sit in their own column; each stage adds one column of `group` tiles.
  const size=18,gap=3,cell=size+gap,height=Math.max(v.fixed,v.group)*cell;
  body=<div className="flex flex-wrap items-end justify-center gap-6">{Array.from({length:v.stages},(_,i)=>{const columns=[v.fixed,...Array(i+1).fill(v.group)],width=columns.length*cell+8;return <figure key={i} className="m-0 text-center"><svg viewBox={`0 0 ${width} ${height}`} style={{width:width*1.4,height:height*1.4}} aria-hidden="true">{columns.flatMap((count,c)=>Array.from({length:count},(_,r)=><rect key={`${c}-${r}`} x={c*cell+(c?8:0)} y={height-(r+1)*cell} width={size} height={size} rx="3" fill={t.ctaFrom} opacity={c?0.85:0.55}/>))}</svg><figcaption className="mt-1 text-sm font-bold">Stage {i+1}</figcaption></figure>;})}</div>;
 }
 else if(v.kind==='balance')body=<svg viewBox="0 0 520 190" className="mx-auto max-h-56 w-full" role="img" aria-label={cave7VisualSpeech(v)}><path d="M260 60V172M215 172H305" stroke="#475569" strokeWidth="6" strokeLinecap="round"/><path d="M110 60H410" stroke="#475569" strokeWidth="6" strokeLinecap="round"/><path d="M110 60L45 118M110 60L175 118M410 60L345 118M410 60L475 118" stroke="#94a3b8" strokeWidth="2"/><rect x="20" y="118" width="180" height="46" rx="10" fill="#f1f5f9" stroke="#64748b"/><rect x="320" y="118" width="180" height="46" rx="10" fill="#f1f5f9" stroke="#64748b"/><text x="110" y="148" textAnchor="middle" fontSize="22" fontWeight="700" fill="#0f172a">{v.left}</text><text x="410" y="148" textAnchor="middle" fontSize="22" fontWeight="700" fill="#0f172a">{v.right}</text><text x="260" y="32" textAnchor="middle" fontSize="16" fill="#334155">The scale is balanced</text></svg>;
 else if(v.kind==='chance')body=<><ChanceVisual visual={v.apparatus}/><p className="mt-2 text-center">{v.caption}</p></>;
 else if(v.kind==='frequency'){
  const max=Math.max(1,...v.counts),bar=440/v.values.length;
  body=<svg viewBox="0 0 520 280" className="mx-auto max-h-72 w-full" role="img" aria-label={cave7VisualSpeech(v)}><path d="M55 20V220H505" fill="none" stroke="#475569"/>{v.values.map((n,i)=><g key={i}><rect x={60+i*bar} y={220-v.counts[i]/max*170} width={Math.max(8,bar-10)} height={v.counts[i]/max*170} fill={t.ctaFrom}/><text x={60+i*bar+(bar-10)/2} y={210-v.counts[i]/max*170} textAnchor="middle" fill="#1e293b">{v.counts[i]}</text><text x={60+i*bar+(bar-10)/2} y="243" textAnchor="middle" fill="#1e293b">{n}</text></g>)}<text x="270" y="270" textAnchor="middle" fill="#1e293b">{v.unit}</text><text x="5" y="15" fill="#1e293b">Frequency</text></svg>;
 }else{
  const step=v.yStep??Math.max(1,Math.ceil(Math.max(1,...v.points.map(p=>p[1]))/5)),ticks=Math.max(4,Math.ceil(Math.max(1,...v.points.map(p=>p[1]))/step)),minX=Math.min(0,...v.points.map(p=>p[0])),maxX=Math.max(1,...v.points.map(p=>p[0])),minY=0,maxY=ticks*step,px=(x:number)=>65+(x-minX)/(maxX-minX)*410,py=(y:number)=>230-(y-minY)/(maxY-minY)*190;
  body=<svg viewBox="0 0 540 300" className="mx-auto max-h-80 w-full" role="img" aria-label={cave7VisualSpeech(v)}>{Array.from({length:ticks+1},(_,i)=>{const y=i*step;return <g key={i}><path d={`M65 ${py(y)}H475`} stroke="#e2e8f0"/><text x="55" y={py(y)+5} textAnchor="end" fill="#334155">{Math.round(y*100)/100}</text></g>;})}<path d="M65 30V230H490" fill="none" stroke="#475569"/>{v.connect&&<polyline points={v.points.map(p=>`${px(p[0])},${py(p[1])}`).join(' ')} fill="none" stroke={t.ctaFrom} strokeWidth="3"/>}{v.points.map((p,i)=><g key={i}><circle cx={px(p[0])} cy={py(p[1])} r="5" fill={t.ctaFrom}/><text x={px(p[0])} y="254" textAnchor="middle" fill="#334155">{p[0]}</text>{v.showValues&&<text x={px(p[0])} y={py(p[1])-11} textAnchor="middle" fill="#334155">{p[1]}</text>}</g>)}<text x="270" y="282" textAnchor="middle" fill="#1e293b">{v.xLabel}</text><text x="65" y="16" fill="#1e293b">{v.yLabel}</text></svg>;
 }
 return <section className="my-4 rounded-xl border bg-white p-4 text-slate-900" style={{borderColor:t.ctaFrom}}><div className="mb-3 flex items-start justify-between gap-3"><h3 className="font-bold">{v.title}</h3><ReadAloudBtn text={cave7VisualSpeech(v)} label="Read diagram"/></div>{body}</section>;
}
