'use client';
import {useState} from 'react';
import ReadAloudBtn from '@/components/ReadAloudBtn';
import {foldNet,type Cell} from '@/data/activities/starpath/level5/nets';
import {CubeNet} from '@/components/starpath/Level5StarpathAssessmentCard';
import {Plans,Plane} from '@/components/starpath/Level7StarpathAssessmentCard';
import Level7Flowchart from '@/components/starpath/Level7Flowchart';
import type {Level7Response} from '@/lib/starpath-level7-review';
import type {P7} from '@/data/assessments/revisions/level7StarpathFiveForms';
const button='rounded-lg border border-violet-400 bg-white px-3 py-2 font-bold text-violet-950 focus-visible:outline-2 focus-visible:outline-offset-2';
const start=[{x:-3,y:1},{x:-1,y:1},{x:-3,y:3}];
const empty:Level7Response={selected:[],value:'',pair:{x:'',y:''},points:[],commands:[],assignments:{},decisions:[]};
export default function Space7LearningLab({week}:{week:number}){
 const [cells,setCells]=useState<Cell[]>([]),[heights,setHeights]=useState([1,2,0,2,1,3]),[move,setMove]=useState('translate'),[response,setResponse]=useState(empty),[decisions,setDecisions]=useState(['','']),[families,setFamilies]=useState<string[]>([]),[feedback,setFeedback]=useState('');
 const expected:P7[]=start.map(p=>move==='translate'?{x:p.x+2,y:p.y-1}:move==='reflect'?{x:-p.x,y:p.y}:{x:p.y,y:-p.x});
 const instruction=week===1?'Select six joined grid squares to build a cube net, then test the folds.':week<=3?'Change stack heights to construct a cube model. Then compare its front and side views.':week<=5||week===9?'A square has four equal sides and four right angles. Select every family it belongs to.':week<=8?'Construct the image of the triangle: choose a move, then select its three final vertices on the grid.':'Complete a classification algorithm. The first decision is “Four right angles?”. Choose the next test on each branch.';
 return <details className="mt-5 rounded-xl border border-violet-300 bg-white p-4 text-slate-900"><summary className="cursor-pointer text-lg font-bold">Try it yourself · build and test</summary><div className="mt-4"><div className="flex justify-between gap-3"><p>{instruction}</p><ReadAloudBtn text={instruction}/></div>
 {week===1?<><div className="mx-auto my-4 grid max-w-80 grid-cols-6 gap-1">{Array.from({length:30},(_,i)=>{const r=Math.floor(i/6),c=i%6,on=cells.some(p=>p.r===r&&p.c===c);return <button key={i} aria-label={`Row ${r+1}, column ${c+1}`} aria-pressed={on} className={`aspect-square rounded border ${on?'bg-violet-500 text-white':'bg-white'}`} onClick={()=>{setCells(xs=>on?xs.filter(p=>p.r!==r||p.c!==c):xs.length<6?[...xs,{r,c}]:xs);setFeedback('');}}>{on?'■':'·'}</button>;})}</div>{cells.length>0&&<div className="mx-auto max-w-64"><CubeNet cells={cells}/><ReadAloudBtn text={cells.map(p=>`Square at row ${p.r+1}, column ${p.c+1}`).join('. ')} label="Read your net"/></div>}<button className={button} onClick={()=>setFeedback(cells.length!==6?'A cube needs exactly six squares.':foldNet(cells).valid?'This net folds to six distinct cube faces. Explain which faces will meet.':'This arrangement does not fold to six distinct cube faces. Check connections and overlapping faces.')}>Test my net</button></>:
 week<=3?<><div className="my-4 grid grid-cols-3 gap-3">{heights.map((h,i)=><label key={i}>{i<3?'Back':'Front'} row, column {i%3+1}<input aria-label={`${i<3?'Back':'Front'} row column ${i%3+1} height`} type="number" min="0" max="4" value={h} className="mt-1 w-full rounded border p-2" onChange={e=>setHeights(xs=>xs.map((x,j)=>i===j?Math.max(0,Math.min(4,Math.trunc(Number(e.target.value)))):x))}/></label>)}</div><Plans t={{mode:'choice',diagram:'plans',instruction:'Your model',cols:3,rows:2,heights,showModel:true}}/><ReadAloudBtn text={`Your height plan: back row ${heights.slice(0,3).join(', ')}; front row ${heights.slice(3).join(', ')}. Zero is empty.`} label="Read your model"/><button className={button} onClick={()=>setFeedback(`Front heights, left to right: ${[0,1,2].map(i=>Math.max(heights[i],heights[i+3])).join(', ')}. Side heights, back row first: ${Math.max(...heights.slice(0,3))}, ${Math.max(...heights.slice(3))}. Total cubes: ${heights.reduce((s,n)=>s+n,0)}.`)}>Compare views</button></>:
 week<=5||week===9?<><div className="my-4 flex flex-wrap gap-3">{['Rectangle','Rhombus','Parallelogram','Triangle'].map(name=><label key={name} className="rounded border p-3"><input type="checkbox" checked={families.includes(name)} onChange={()=>setFamilies(xs=>xs.includes(name)?xs.filter(s=>s!==name):[...xs,name])}/> {name}</label>)}</div><ReadAloudBtn text="Choices: rectangle, rhombus, parallelogram, triangle. Select every family that includes a square."/><button className={button} onClick={()=>setFeedback(families.length===3&&!families.includes('Triangle')?'Correct. A square satisfies the rectangle, rhombus and parallelogram definitions.':'Check all three properties: four right angles, four equal sides and two pairs of parallel sides.')}>Test classification</button></>:
 week<=8?<><label className="my-3 block">Transformation <select className="ml-2 rounded border p-2" value={move} onChange={e=>{setMove(e.target.value);setResponse(empty);setFeedback('');}}><option value="translate">Translate 2 right, 1 down</option><option value="reflect">Reflect in the y-axis</option><option value="rotate">Rotate 90° clockwise about the origin</option></select></label><div className="mx-auto max-w-lg"><Plane t={{mode:'points',diagram:'plane',instruction:'Construct the image.',shape:start,expected}} a={response} onChange={setResponse}/></div><ReadAloudBtn text={`Original vertices: ${start.map(p=>`(${p.x}, ${p.y})`).join('; ')}. Move: ${move==='translate'?'two right and one down':move==='reflect'?'reflect in the y-axis':'rotate ninety degrees clockwise about the origin'}. Selected vertices: ${response.points.map(p=>`(${p.x}, ${p.y})`).join('; ')||'none'}.`} label="Read construction"/><button className={button} onClick={()=>setFeedback(response.points.length===3&&expected.every(p=>response.points.some(q=>q.x===p.x&&q.y===p.y))?'Correct. The image has the same side lengths and angles.':'Apply the selected move to each original vertex. Select exactly three final vertices.')}>Check image</button><button className={`${button} ml-2`} onClick={()=>{setResponse(empty);setFeedback('');}}>Reset points</button></>:
 <><Level7Flowchart tree={{question:'Four right angles?',yes:{question:'Choose the next test on Yes',slot:0,yes:'Square',no:'Non-square rectangle'},no:{question:'Choose the next test on No',slot:1,yes:'Non-square rhombus',no:'Other quadrilateral'}}} choices={['Four equal sides?','At least one equal pair?','Three sides?']} answers={decisions} onDecision={(i,value)=>setDecisions(xs=>xs.map((x,j)=>i===j?value:x))}/><ReadAloudBtn text={`First test: four right angles. Yes branch uses ${decisions[0]||'an unfinished decision'}: Yes outputs square, No outputs non-square rectangle. No branch uses ${decisions[1]||'an unfinished decision'}: Yes outputs non-square rhombus, No outputs other quadrilateral. Available tests: four equal sides, at least one equal pair, three sides.`} label="Read algorithm"/><button className={button} onClick={()=>setFeedback(decisions.every(s=>s==='Four equal sides?')?'The algorithm passes all four test families. Explain why a square needs both properties.':'Test the paths for a square, non-square rectangle, non-square rhombus and other quadrilateral. Which property distinguishes the remaining pairs?')}>Run four test cases</button></>}
 {feedback&&<div className="mt-4 flex items-start justify-between gap-3 rounded bg-violet-50 p-3"><p aria-live="polite">{feedback}</p><ReadAloudBtn text={feedback}/></div>}
 </div></details>;
}
