-- Additive XP train catalogue. Existing inventories, balances and student RPC guards are unchanged.
-- Existing placed free starter trains remain compatible in the client.
begin;
insert into public.economy_items (item_key, name, description, category, realm_id, rarity, price, icon, accent, active, purchasable, discoverable, sort_order, metadata) values
('train_steam', 'Little Steam Engine', 'A brass-trimmed steam engine with a tall chimney and bright headlamp. Place on existing rails. Includes its carriages; follows a closed loop and stops at stations.', 'decoration', null, 'common', 400, 'train-front', '#347367', true, true, true, 200, '{"slot":"world_train","worldAssetKey":"train_steam","worldArea":"trains","marketplaceCategory":"trains","realmCollection":"general","gridSize":"1x1","tier":1,"marketplace_visual":{"type":"asset","src":"/marketplace/world-renders/train_steam.webp","alt":"Little Steam Engine — actual world model","previewMode":"world"}}'),
('train_country', 'Country Passenger Train', 'A heritage diesel with a cream roof and a window-lined passenger carriage. Place on existing rails. Includes its carriages; follows a closed loop and stops at stations.', 'decoration', null, 'rare', 900, 'train-front', '#a63935', true, true, true, 201, '{"slot":"world_train","worldAssetKey":"train_country","worldArea":"trains","marketplaceCategory":"trains","realmCollection":"general","gridSize":"1x1","tier":2,"marketplace_visual":{"type":"asset","src":"/marketplace/world-renders/train_country.webp","alt":"Country Passenger Train — actual world model","previewMode":"world"}}'),
('train_freight', 'Freight Train', 'An industrial shunter pulling a timber wagon and a covered cargo wagon. Place on existing rails. Includes its carriages; follows a closed loop and stops at stations.', 'decoration', null, 'rare', 1400, 'train-front', '#d38736', true, true, true, 202, '{"slot":"world_train","worldAssetKey":"train_freight","worldArea":"trains","marketplaceCategory":"trains","realmCollection":"general","gridSize":"1x1","tier":2,"marketplace_visual":{"type":"asset","src":"/marketplace/world-renders/train_freight.webp","alt":"Freight Train — actual world model","previewMode":"world"}}'),
('train_express', 'Modern Express', 'A streamlined electric express with a swept nose and panoramic windows. Place on existing rails. Includes its carriages; follows a closed loop and stops at stations.', 'decoration', null, 'legendary', 2200, 'train-front', '#e4edf0', true, true, true, 203, '{"slot":"world_train","worldAssetKey":"train_express","worldArea":"trains","marketplaceCategory":"trains","realmCollection":"general","gridSize":"1x1","tier":3,"marketplace_visual":{"type":"asset","src":"/marketplace/world-renders/train_express.webp","alt":"Modern Express — actual world model","previewMode":"world"}}'),
('train_number', 'Number Nexus Circuit Train', 'An angular circuit engine with a glowing cube reactor and digital cargo. Place on existing rails. Includes its carriages; follows a closed loop and stops at stations.', 'decoration', null, 'legendary', 3000, 'train-front', '#164d58', true, true, true, 204, '{"slot":"world_train","worldAssetKey":"train_number","worldArea":"trains","marketplaceCategory":"trains","realmCollection":"number","gridSize":"1x1","tier":3,"marketplace_visual":{"type":"asset","src":"/marketplace/world-renders/train_number.webp","alt":"Number Nexus Circuit Train — actual world model","previewMode":"world"}}'),
('train_measurement', 'Measurelands Clockwork Train', 'A copper boiler engine with measuring bands, clockwork wheels and a survey carriage. Place on existing rails. Includes its carriages; follows a closed loop and stops at stations.', 'decoration', null, 'legendary', 3000, 'train-front', '#71452c', true, true, true, 205, '{"slot":"world_train","worldAssetKey":"train_measurement","worldArea":"trains","marketplaceCategory":"trains","realmCollection":"measurement","gridSize":"1x1","tier":3,"marketplace_visual":{"type":"asset","src":"/marketplace/world-renders/train_measurement.webp","alt":"Measurelands Clockwork Train — actual world model","previewMode":"world"}}'),
('train_space', 'Starpath Comet Train', 'A rocket-nosed engine with swept fins, glowing thrusters and an observatory carriage. Place on existing rails. Includes its carriages; follows a closed loop and stops at stations.', 'decoration', null, 'legendary', 3000, 'train-front', '#302a6a', true, true, true, 206, '{"slot":"world_train","worldAssetKey":"train_space","worldArea":"trains","marketplaceCategory":"trains","realmCollection":"space","gridSize":"1x1","tier":3,"marketplace_visual":{"type":"asset","src":"/marketplace/world-renders/train_space.webp","alt":"Starpath Comet Train — actual world model","previewMode":"world"}}'),
('train_pattern', 'Pattern Peaks Prism Train', 'A faceted engine crowned with repeating crystal spires and a mosaic carriage. Place on existing rails. Includes its carriages; follows a closed loop and stops at stations.', 'decoration', null, 'legendary', 3000, 'train-front', '#047857', true, true, true, 207, '{"slot":"world_train","worldAssetKey":"train_pattern","worldArea":"trains","marketplaceCategory":"trains","realmCollection":"pattern","gridSize":"1x1","tier":3,"marketplace_visual":{"type":"asset","src":"/marketplace/world-renders/train_pattern.webp","alt":"Pattern Peaks Prism Train — actual world model","previewMode":"world"}}'),
('train_statistics', 'Statistica Survey Train', 'A research locomotive with rooftop scanning dishes and a mobile data laboratory. Place on existing rails. Includes its carriages; follows a closed loop and stops at stations.', 'decoration', null, 'legendary', 3000, 'train-front', '#a83e4b', true, true, true, 208, '{"slot":"world_train","worldAssetKey":"train_statistics","worldArea":"trains","marketplaceCategory":"trains","realmCollection":"statistics","gridSize":"1x1","tier":3,"marketplace_visual":{"type":"asset","src":"/marketplace/world-renders/train_statistics.webp","alt":"Statistica Survey Train — actual world model","previewMode":"world"}}'),
('train_chance', 'Chance Hollow Fortune Train', 'A lantern-lit engine with a domed roof and a dice-topped treasure carriage. Place on existing rails. Includes its carriages; follows a closed loop and stops at stations.', 'decoration', null, 'legendary', 3000, 'train-front', '#be3455', true, true, true, 209, '{"slot":"world_train","worldAssetKey":"train_chance","worldArea":"trains","marketplaceCategory":"trains","realmCollection":"chance","gridSize":"1x1","tier":3,"marketplace_visual":{"type":"asset","src":"/marketplace/world-renders/train_chance.webp","alt":"Chance Hollow Fortune Train — actual world model","previewMode":"world"}}')
on conflict (item_key) do nothing;
commit;
