-- Six complete realm outfits. Existing avatar_outfit slot and guarded purchase/equip RPCs.
-- Hand equipment remains a separate purchase; no session or permission changes.
begin;
insert into public.economy_items
(item_key,name,description,category,realm_id,rarity,price,icon,accent,active,purchasable,discoverable,sort_order,metadata)
values
('avatar_outfit_equationator','Equationator Tech Suit','Segmented blue armour, gold equals badge and reinforced boots. Outfit only; character equipment is sold separately.','avatar',null,'rare',1000,'Shirt','#2889ad',true,true,false,620,'{"slot":"avatar_outfit","top":"realm_equationator","bottom":"joggers","shoeStyle":"boots","shirt":"#2889ad","shirtTrim":"#f4c856","pants":"#18343f","shoes":"#327f9b","realmCollection":"number"}'),
('avatar_outfit_timewielder','Timewielder Robes','Split violet robes, clockwork medallion and gold measuring marks. Outfit only; character equipment is sold separately.','avatar',null,'legendary',1600,'Shirt','#493373',true,true,false,621,'{"slot":"avatar_outfit","top":"realm_timewielder","bottom":"joggers","shoeStyle":"boots","shirt":"#493373","shirtTrim":"#dfb961","pants":"#29314b","shoes":"#69517f","realmCollection":"measurement"}'),
('avatar_outfit_starweaver','Starweaver Celestial Suit','Layered constellation panels, asymmetric shoulder mantle and star brooch. Outfit only; character equipment is sold separately.','avatar',null,'legendary',1500,'Shirt','#6445a0',true,true,false,622,'{"slot":"avatar_outfit","top":"realm_starweaver","bottom":"joggers","shoeStyle":"boots","shirt":"#6445a0","shirtTrim":"#ecdb99","pants":"#3d346c","shoes":"#9b83c8","realmCollection":"space"}'),
('avatar_outfit_codemaster','Codemaster Crystal Armour','Dark angular plates, violet crystal shoulders and repeating gold diamonds. Outfit only; character equipment is sold separately.','avatar',null,'legendary',1600,'Shirt','#30263f',true,true,false,623,'{"slot":"avatar_outfit","top":"realm_codemaster","bottom":"joggers","shoeStyle":"boots","shirt":"#30263f","shirtTrim":"#b79860","pants":"#292536","shoes":"#494052","realmCollection":"pattern"}'),
('avatar_outfit_insightkeeper','Insightkeeper Field Coat','Ivory long coat, navy waistcoat, cyan crystal clasp and chart pocket. Outfit only; character equipment is sold separately.','avatar',null,'rare',1000,'Shirt','#eee2c9',true,true,false,624,'{"slot":"avatar_outfit","top":"realm_insightkeeper","bottom":"joggers","shoeStyle":"boots","shirt":"#eee2c9","shirtTrim":"#caad65","pants":"#243e53","shoes":"#ece4d3","realmCollection":"statistics"}'),
('avatar_outfit_chanzia','Chanzia Shadow Wraps','Layered plum wraps, lowered hood, diagonal sash and glowing spiral badge. Outfit only; character equipment is sold separately.','avatar',null,'legendary',1400,'Shirt','#392544',true,true,false,625,'{"slot":"avatar_outfit","top":"realm_chanzia","bottom":"joggers","shoeStyle":"boots","shirt":"#392544","shirtTrim":"#c67ce2","pants":"#2b243b","shoes":"#50355e","realmCollection":"chance"}')
on conflict (item_key) do nothing;
commit;
