-- Additive village catalogue: existing purchases and session guards are unchanged.
begin;
insert into public.economy_items (item_key, name, description, category, realm_id, rarity, price, icon, accent, active, purchasable, discoverable, sort_order, metadata) values
('central_world_plot_1_village_cottage', 'Village Cottage', 'Build your village in castle, country or coastal style. All three styles and repeat placements included in one unlock. Exterior only.', 'decoration', null, 'common', 350, 'house', '#8b9972', true, true, true, 11, '{"slot":"world_plot_1","worldPlotId":"customisation-plot-1","worldAssetKey":"village_cottage","worldCollection":"country","worldArea":"buildings","marketplaceCategory":"buildings","gridSize":"5x5","tier":1,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/village_cottage.png","alt":"Village Cottage central world customisation preview","previewMode":"background"}}'),
('central_world_plot_1_village_family_house', 'Family House', 'Build your village in castle, country or coastal style. All three styles and repeat placements included in one unlock. Exterior only.', 'decoration', null, 'rare', 850, 'house', '#8b9972', true, true, true, 12, '{"slot":"world_plot_1","worldPlotId":"customisation-plot-1","worldAssetKey":"village_family_house","worldCollection":"country","worldArea":"buildings","marketplaceCategory":"buildings","gridSize":"6x6","tier":2,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/village_family_house.png","alt":"Family House central world customisation preview","previewMode":"background"}}'),
('central_world_plot_1_village_townhouse', 'Village Townhouse', 'Build your village in castle, country or coastal style. All three styles and repeat placements included in one unlock. Exterior only.', 'decoration', null, 'rare', 650, 'building', '#8b9972', true, true, true, 12, '{"slot":"world_plot_1","worldPlotId":"customisation-plot-1","worldAssetKey":"village_townhouse","worldCollection":"country","worldArea":"buildings","marketplaceCategory":"buildings","gridSize":"4x5","tier":2,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/village_townhouse.png","alt":"Village Townhouse central world customisation preview","previewMode":"background"}}'),
('central_world_plot_1_village_manor', 'Grand Manor', 'Build your village in castle, country or coastal style. All three styles and repeat placements included in one unlock. Exterior only.', 'decoration', null, 'legendary', 2200, 'landmark', '#8b9972', true, true, true, 13, '{"slot":"world_plot_1","worldPlotId":"customisation-plot-1","worldAssetKey":"village_manor","worldCollection":"country","worldArea":"buildings","marketplaceCategory":"buildings","gridSize":"9x7","tier":3,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/village_manor.png","alt":"Grand Manor central world customisation preview","previewMode":"background"}}'),
('central_world_plot_1_village_store', 'General Store', 'Build your village in castle, country or coastal style. All three styles and repeat placements included in one unlock. Exterior only.', 'decoration', null, 'rare', 600, 'store', '#8b9972', true, true, true, 12, '{"slot":"world_plot_1","worldPlotId":"customisation-plot-1","worldAssetKey":"village_store","worldCollection":"country","worldArea":"buildings","marketplaceCategory":"buildings","gridSize":"6x5","tier":2,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/village_store.png","alt":"General Store central world customisation preview","previewMode":"background"}}'),
('central_world_plot_1_village_cafe', 'Village Café', 'Build your village in castle, country or coastal style. All three styles and repeat placements included in one unlock. Exterior only.', 'decoration', null, 'rare', 750, 'coffee', '#8b9972', true, true, true, 12, '{"slot":"world_plot_1","worldPlotId":"customisation-plot-1","worldAssetKey":"village_cafe","worldCollection":"country","worldArea":"buildings","marketplaceCategory":"buildings","gridSize":"7x7","tier":2,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/village_cafe.png","alt":"Village Café central world customisation preview","previewMode":"background"}}'),
('central_world_plot_1_village_library', 'Village Library', 'Build your village in castle, country or coastal style. All three styles and repeat placements included in one unlock. Exterior only.', 'decoration', null, 'rare', 1200, 'book-open', '#8b9972', true, true, true, 12, '{"slot":"world_plot_1","worldPlotId":"customisation-plot-1","worldAssetKey":"village_library","worldCollection":"country","worldArea":"buildings","marketplaceCategory":"buildings","gridSize":"7x6","tier":2,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/village_library.png","alt":"Village Library central world customisation preview","previewMode":"background"}}'),
('central_world_plot_1_village_town_hall', 'Town Hall', 'Build your village in castle, country or coastal style. All three styles and repeat placements included in one unlock. Exterior only.', 'decoration', null, 'legendary', 1800, 'landmark', '#8b9972', true, true, true, 13, '{"slot":"world_plot_1","worldPlotId":"customisation-plot-1","worldAssetKey":"village_town_hall","worldCollection":"country","worldArea":"buildings","marketplaceCategory":"buildings","gridSize":"8x7","tier":3,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/village_town_hall.png","alt":"Town Hall central world customisation preview","previewMode":"background"}}'),
('central_world_plot_1_village_apartments', 'City Apartment Tower', 'Build a city neighbourhood with a ten-storey apartment tower. Unlock once, place multiple copies and choose your colours. Exterior only.', 'decoration', null, 'legendary', 2800, 'building-2', '#8b9972', true, true, true, 13, '{"slot":"world_plot_1","worldPlotId":"customisation-plot-1","worldAssetKey":"village_apartments","worldCollection":"country","worldArea":"buildings","marketplaceCategory":"buildings","gridSize":"7x7","tier":3,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/village_apartments.png","alt":"City Apartment Tower central world customisation preview","previewMode":"background"}}')
on conflict (item_key) do nothing;
commit;
