begin;

update public.economy_items
set active = false,
    purchasable = false,
    discoverable = false
where item_key like 'central_world_plot_%';

insert into public.economy_items (
  item_key, name, description, category, realm_id, rarity, price, icon, accent,
  purchasable, discoverable, sort_order, metadata
) values
  ('central_world_plot_1_clubhouse', 'Clubhouse', 'Your place to hang out and relax with friends.', 'decoration', null, 'rare', 800, 'house', '#2563eb', true, false, 811, '{"slot":"world_plot_1","worldPlotId":"customisation-plot-1","worldAssetKey":"clubhouse","worldArea":"buildings","marketplaceCategory":"buildings","gridSize":"4x4","tier":2,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/clubhouse.webp","alt":"Clubhouse central world reward preview","previewMode":"background"}}'),
  ('central_world_plot_1_games_room', 'Games Room', 'Arcade games, challenges and tons of fun.', 'decoration', null, 'legendary', 2400, 'gamepad-2', '#7c3aed', true, false, 812, '{"slot":"world_plot_1","worldPlotId":"customisation-plot-1","worldAssetKey":"games_room","worldArea":"buildings","marketplaceCategory":"buildings","gridSize":"4x4","tier":3,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/games_room.webp","alt":"Games Room central world reward preview","previewMode":"background"}}'),
  ('central_world_plot_1_treehouse', 'Treehouse', 'A cosy hideout up in the trees.', 'decoration', null, 'common', 200, 'tree-pine', '#16a34a', true, false, 813, '{"slot":"world_plot_1","worldPlotId":"customisation-plot-1","worldAssetKey":"treehouse","worldArea":"buildings","marketplaceCategory":"buildings","gridSize":"2x2","tier":1,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/treehouse.webp","alt":"Treehouse central world reward preview","previewMode":"background"}}'),
  ('central_world_plot_2_training_centre', 'Training Centre', 'Train, level up and get stronger every day.', 'decoration', null, 'common', 200, 'dumbbell', '#22c55e', true, false, 821, '{"slot":"world_plot_2","worldPlotId":"customisation-plot-2","worldAssetKey":"training_centre","worldArea":"buildings","marketplaceCategory":"buildings","gridSize":"3x3","tier":1,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/training_centre.webp","alt":"Training Centre central world reward preview","previewMode":"background"}}'),
  ('central_world_plot_2_workshop', 'Workshop', 'Build, create and invent awesome things.', 'decoration', null, 'rare', 800, 'wrench', '#0ea5e9', true, false, 822, '{"slot":"world_plot_2","worldPlotId":"customisation-plot-2","worldAssetKey":"workshop","worldArea":"buildings","marketplaceCategory":"buildings","gridSize":"3x3","tier":2,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/workshop.webp","alt":"Workshop central world reward preview","previewMode":"background"}}'),
  ('central_world_plot_2_observatory', 'Observatory', 'Explore the stars and unlock cosmic discoveries.', 'decoration', null, 'legendary', 2400, 'telescope', '#8b5cf6', true, false, 823, '{"slot":"world_plot_2","worldPlotId":"customisation-plot-2","worldAssetKey":"observatory","worldArea":"buildings","marketplaceCategory":"buildings","gridSize":"4x4","tier":3,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/observatory.webp","alt":"Observatory central world reward preview","previewMode":"background"}}'),
  ('central_world_plot_3_puppy_yard', 'Puppy Yard', 'A playful yard for happy puppies.', 'decoration', null, 'common', 200, 'paw-print', '#f59e0b', true, false, 831, '{"slot":"world_plot_3","worldPlotId":"customisation-plot-3","worldAssetKey":"puppy_yard","worldArea":"animals","marketplaceCategory":"animals","gridSize":"3x3","tier":1,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/puppy_yard.webp","alt":"Puppy Yard central world reward preview","previewMode":"background"}}'),
  ('central_world_plot_3_bunny_garden', 'Bunny Garden', 'A soft garden full of bunny burrows and carrots.', 'decoration', null, 'common', 200, 'carrot', '#f472b6', true, false, 832, '{"slot":"world_plot_3","worldPlotId":"customisation-plot-3","worldAssetKey":"bunny_garden","worldArea":"animals","marketplaceCategory":"animals","gridSize":"3x3","tier":1,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/bunny_garden.webp","alt":"Bunny Garden central world reward preview","previewMode":"background"}}'),
  ('central_world_plot_3_pony_paddock', 'Pony Paddock', 'A bright paddock for ponies to trot around.', 'decoration', null, 'rare', 800, 'horseshoe', '#a16207', true, false, 833, '{"slot":"world_plot_3","worldPlotId":"customisation-plot-3","worldAssetKey":"pony_paddock","worldArea":"animals","marketplaceCategory":"animals","gridSize":"4x3","tier":2,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/pony_paddock.webp","alt":"Pony Paddock central world reward preview","previewMode":"background"}}'),
  ('central_world_plot_4_farmyard', 'Farmyard', 'A cheerful farm space with animals and hay bales.', 'decoration', null, 'rare', 800, 'barn', '#84cc16', true, false, 841, '{"slot":"world_plot_4","worldPlotId":"customisation-plot-4","worldAssetKey":"farmyard","worldArea":"animals","marketplaceCategory":"animals","gridSize":"4x4","tier":2,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/farmyard.webp","alt":"Farmyard central world reward preview","previewMode":"background"}}'),
  ('central_world_plot_4_wildlife_habitat', 'Wildlife Habitat', 'A nature habitat for curious wildlife.', 'decoration', null, 'legendary', 2400, 'trees', '#059669', true, false, 842, '{"slot":"world_plot_4","worldPlotId":"customisation-plot-4","worldAssetKey":"wildlife_habitat","worldArea":"animals","marketplaceCategory":"animals","gridSize":"4x4","tier":3,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/wildlife_habitat.webp","alt":"Wildlife Habitat central world reward preview","previewMode":"background"}}'),
  ('central_world_plot_5_backyard_pool', 'Backyard Pool', 'A cool pool for sunny days in your world.', 'decoration', null, 'common', 200, 'waves', '#0ea5e9', true, false, 851, '{"slot":"world_plot_5","worldPlotId":"customisation-plot-5","worldAssetKey":"backyard_pool","worldArea":"pools_play","marketplaceCategory":"pools_play","gridSize":"3x2","tier":1,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/backyard_pool.webp","alt":"Backyard Pool central world reward preview","previewMode":"background"}}'),
  ('central_world_plot_5_splash_pool', 'Splash Pool', 'A colourful splash zone with fountains.', 'decoration', null, 'rare', 800, 'waves', '#06b6d4', true, false, 852, '{"slot":"world_plot_5","worldPlotId":"customisation-plot-5","worldAssetKey":"splash_pool","worldArea":"pools_play","marketplaceCategory":"pools_play","gridSize":"3x3","tier":2,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/splash_pool.webp","alt":"Splash Pool central world reward preview","previewMode":"background"}}'),
  ('central_world_plot_5_water_park', 'Water Park', 'Slides, water jets and a huge fun zone.', 'decoration', null, 'legendary', 2400, 'waves', '#0284c7', true, false, 853, '{"slot":"world_plot_5","worldPlotId":"customisation-plot-5","worldAssetKey":"water_park","worldArea":"pools_play","marketplaceCategory":"pools_play","gridSize":"4x4","tier":3,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/water_park.webp","alt":"Water Park central world reward preview","previewMode":"background"}}'),
  ('central_world_plot_6_adventure_playground', 'Adventure Playground', 'Climbing towers, slides and places to explore.', 'decoration', null, 'rare', 800, 'mountain', '#f97316', true, false, 861, '{"slot":"world_plot_6","worldPlotId":"customisation-plot-6","worldAssetKey":"adventure_playground","worldArea":"pools_play","marketplaceCategory":"pools_play","gridSize":"4x3","tier":2,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/adventure_playground.webp","alt":"Adventure Playground central world reward preview","previewMode":"background"}}'),
  ('central_world_plot_6_trampoline_park', 'Trampoline Park', 'Bounce high in a park made for energy.', 'decoration', null, 'common', 200, 'circle-dot', '#22c55e', true, false, 862, '{"slot":"world_plot_6","worldPlotId":"customisation-plot-6","worldAssetKey":"trampoline_park","worldArea":"pools_play","marketplaceCategory":"pools_play","gridSize":"3x3","tier":1,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/trampoline_park.webp","alt":"Trampoline Park central world reward preview","previewMode":"background"}}'),
  ('central_world_plot_7_sports_stadium', 'Sports Stadium', 'Compete and celebrate your biggest wins.', 'decoration', null, 'rare', 800, 'trophy', '#2563eb', true, false, 871, '{"slot":"world_plot_7","worldPlotId":"customisation-plot-7","worldAssetKey":"sports_stadium","worldArea":"special","marketplaceCategory":"special","gridSize":"4x4","tier":2,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/sports_stadium.webp","alt":"Sports Stadium central world reward preview","previewMode":"background"}}'),
  ('central_world_plot_7_cinema', 'Cinema', 'Watch movies with friends in your own cinema.', 'decoration', null, 'legendary', 2400, 'clapperboard', '#dc2626', true, false, 872, '{"slot":"world_plot_7","worldPlotId":"customisation-plot-7","worldAssetKey":"cinema","worldArea":"special","marketplaceCategory":"special","gridSize":"3x3","tier":3,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/cinema.webp","alt":"Cinema central world reward preview","previewMode":"background"}}'),
  ('central_world_plot_7_arcade', 'Arcade', 'Retro games and high score challenges.', 'decoration', null, 'rare', 800, 'joystick', '#a855f7', true, false, 873, '{"slot":"world_plot_7","worldPlotId":"customisation-plot-7","worldAssetKey":"arcade","worldArea":"special","marketplaceCategory":"special","gridSize":"3x3","tier":2,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/arcade.webp","alt":"Arcade central world reward preview","previewMode":"background"}}'),
  ('central_world_plot_8_party_house', 'Party House', 'The perfect spot for parties and celebrations.', 'decoration', null, 'common', 200, 'party-popper', '#ec4899', true, false, 881, '{"slot":"world_plot_8","worldPlotId":"customisation-plot-8","worldAssetKey":"party_house","worldArea":"special","marketplaceCategory":"special","gridSize":"3x3","tier":1,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/party_house.webp","alt":"Party House central world reward preview","previewMode":"background"}}'),
  ('central_world_plot_8_pet_sanctuary', 'Pet Sanctuary', 'A peaceful place for pets to feel at home.', 'decoration', null, 'legendary', 2400, 'heart', '#14b8a6', true, false, 882, '{"slot":"world_plot_8","worldPlotId":"customisation-plot-8","worldAssetKey":"pet_sanctuary","worldArea":"special","marketplaceCategory":"special","gridSize":"4x4","tier":3,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/pet_sanctuary.webp","alt":"Pet Sanctuary central world reward preview","previewMode":"background"}}')
on conflict (item_key) do update set
  name = excluded.name,
  description = excluded.description,
  category = excluded.category,
  realm_id = excluded.realm_id,
  rarity = excluded.rarity,
  price = excluded.price,
  icon = excluded.icon,
  accent = excluded.accent,
  purchasable = excluded.purchasable,
  discoverable = excluded.discoverable,
  active = true,
  sort_order = excluded.sort_order,
  metadata = excluded.metadata;

commit;
