-- Additive catalogue only: preserves existing items, ownership and RPC access guards.
begin;
insert into public.economy_items (item_key, name, description, category, realm_id, rarity, price, icon, accent, active, purchasable, discoverable, sort_order, metadata) values
('central_world_plot_7_opera_house', 'Sydney Opera House', 'Sculptural sail-shaped roofs overlooking your own harbour.', 'decoration', null, 'legendary', 2500, 'landmark', '#8b9972', true, true, true, 73, '{"slot":"world_plot_7","worldPlotId":"customisation-plot-7","worldAssetKey":"opera_house","worldCollection":"coastal","worldArea":"special","marketplaceCategory":"special","gridSize":"5x4","tier":3,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/opera_house.svg","alt":"Sydney Opera House central world customisation preview","previewMode":"background"}}'),
('central_world_plot_7_harbour_bridge', 'Harbour Bridge', 'A steel arch bridge with sandstone pylons and a timber promenade.', 'decoration', null, 'legendary', 2300, 'landmark', '#8b9972', true, true, true, 73, '{"slot":"world_plot_7","worldPlotId":"customisation-plot-7","worldAssetKey":"harbour_bridge","worldCollection":"coastal","worldArea":"special","marketplaceCategory":"special","gridSize":"6x2","tier":3,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/harbour_bridge.svg","alt":"Harbour Bridge central world customisation preview","previewMode":"background"}}'),
('central_world_plot_2_lighthouse', 'Coastal Lighthouse', 'A coastal lookout with a lantern room and keeper’s cottage.', 'decoration', null, 'rare', 1100, 'lamp', '#8b9972', true, true, true, 22, '{"slot":"world_plot_2","worldPlotId":"customisation-plot-2","worldAssetKey":"lighthouse","worldCollection":"coastal","worldArea":"buildings","marketplaceCategory":"buildings","gridSize":"3x3","tier":2,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/lighthouse.svg","alt":"Coastal Lighthouse central world customisation preview","previewMode":"background"}}'),
('central_world_plot_1_beach_huts', 'Beach Bathing Boxes', 'Three colourful timber bathing boxes for your beach village.', 'decoration', null, 'common', 420, 'house', '#8b9972', true, true, true, 11, '{"slot":"world_plot_1","worldPlotId":"customisation-plot-1","worldAssetKey":"beach_huts","worldCollection":"coastal","worldArea":"buildings","marketplaceCategory":"buildings","gridSize":"4x2","tier":1,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/beach_huts.svg","alt":"Beach Bathing Boxes central world customisation preview","previewMode":"background"}}'),
('central_world_plot_2_railway_station', 'Outback Railway Station', 'A country platform with a station clock, canopy and railway track.', 'decoration', null, 'rare', 1200, 'train-front', '#8b9972', true, true, true, 22, '{"slot":"world_plot_2","worldPlotId":"customisation-plot-2","worldAssetKey":"railway_station","worldCollection":"country","worldArea":"buildings","marketplaceCategory":"buildings","gridSize":"5x3","tier":2,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/railway_station.svg","alt":"Outback Railway Station central world customisation preview","previewMode":"background"}}'),
('central_world_plot_1_country_bakery', 'Country Bakery', 'A welcoming weatherboard bakery with an awning and bread display.', 'decoration', null, 'rare', 520, 'croissant', '#8b9972', true, true, true, 12, '{"slot":"world_plot_1","worldPlotId":"customisation-plot-1","worldAssetKey":"country_bakery","worldCollection":"country","worldArea":"buildings","marketplaceCategory":"buildings","gridSize":"3x3","tier":2,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/country_bakery.svg","alt":"Country Bakery central world customisation preview","previewMode":"background"}}'),
('central_world_plot_4_platypus_creek', 'Platypus Creek', 'A reed-lined creek with river stones, driftwood and a resident platypus.', 'decoration', null, 'rare', 760, 'waves', '#8b9972', true, true, true, 42, '{"slot":"world_plot_4","worldPlotId":"customisation-plot-4","worldAssetKey":"platypus_creek","worldCollection":"bush","worldArea":"animals","marketplaceCategory":"animals","gridSize":"4x3","tier":2,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/platypus_creek.svg","alt":"Platypus Creek central world customisation preview","previewMode":"background"}}'),
('central_world_plot_3_wombat_burrows', 'Wombat Burrows', 'Earthy burrows beneath a fallen log, home to two sturdy wombats.', 'decoration', null, 'common', 380, 'paw-print', '#8b9972', true, true, true, 31, '{"slot":"world_plot_3","worldPlotId":"customisation-plot-3","worldAssetKey":"wombat_burrows","worldCollection":"bush","worldArea":"animals","marketplaceCategory":"animals","gridSize":"3x2","tier":1,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/wombat_burrows.svg","alt":"Wombat Burrows central world customisation preview","previewMode":"background"}}'),
('central_world_plot_4_cockatoo_aviary', 'Cockatoo Aviary', 'A spacious mesh aviary with branches and sulphur-crested cockatoos.', 'decoration', null, 'rare', 1050, 'bird', '#8b9972', true, true, true, 42, '{"slot":"world_plot_4","worldPlotId":"customisation-plot-4","worldAssetKey":"cockatoo_aviary","worldCollection":"bush","worldArea":"animals","marketplaceCategory":"animals","gridSize":"3x3","tier":2,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/cockatoo_aviary.svg","alt":"Cockatoo Aviary central world customisation preview","previewMode":"background"}}'),
('central_world_plot_8_wildlife_rescue', 'Wildlife Rescue Centre', 'A bushland care centre with sheltered yards and native wildlife.', 'decoration', null, 'legendary', 1750, 'heart', '#8b9972', true, true, true, 83, '{"slot":"world_plot_8","worldPlotId":"customisation-plot-8","worldAssetKey":"wildlife_rescue","worldCollection":"bush","worldArea":"animals","marketplaceCategory":"animals","gridSize":"5x4","tier":3,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/wildlife_rescue.svg","alt":"Wildlife Rescue Centre central world customisation preview","previewMode":"background"}}'),
('central_world_plot_8_windmill_garden', 'Country Windmill', 'A farm windmill, rainwater tank and garden trough.', 'decoration', null, 'rare', 650, 'wind', '#8b9972', true, true, true, 82, '{"slot":"world_plot_8","worldPlotId":"customisation-plot-8","worldAssetKey":"windmill_garden","worldCollection":"country","worldArea":"special","marketplaceCategory":"special","gridSize":"3x3","tier":2,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/windmill_garden.svg","alt":"Country Windmill central world customisation preview","previewMode":"background"}}'),
('central_world_plot_6_bush_camp', 'Bush Explorer Camp', 'A canvas shelter, map table and camp seats for your next expedition.', 'decoration', null, 'common', 180, 'tent', '#8b9972', true, true, true, 61, '{"slot":"world_plot_6","worldPlotId":"customisation-plot-6","worldAssetKey":"bush_camp","worldCollection":"bush","worldArea":"special","marketplaceCategory":"special","gridSize":"3x3","tier":1,"marketplace_visual":{"type":"asset","src":"/marketplace/central-world/bush_camp.svg","alt":"Bush Explorer Camp central world customisation preview","previewMode":"background"}}')
on conflict (item_key) do nothing;
commit;
