-- Five complete avatar bundles. Uses existing outfit slot and guarded purchase/equip RPCs.
-- Headwear and accessories are included in outfit metadata; independent equipped layers retain precedence.
begin;
insert into public.economy_items (item_key, name, description, category, realm_id, rarity, price, icon, accent, active, purchasable, discoverable, sort_order, metadata) values
('avatar_outfit_trailblazer', 'Trailblazer Explorer', 'A pocketed field vest, compass badge, hiking boots, explorer hat and trail backpack. Matching accessories are included. Separately equipped accessories can be worn over this look.', 'avatar', null, 'common', 400, 'Shirt', '#496b54', true, true, false, 650, '{"slot":"avatar_outfit","realmCollection":"general","top":"adventure_trailblazer","bottom":"joggers","shoeStyle":"boots","shirt":"#b99b64","shirtTrim":"#496b54","pants":"#596442","shoes":"#624535","hat":"explorer","hatColor":"#af8b50","cape":"none","capeColor":"#496b54","backpack":"explorer","backpackColor":"#496b54","held":"none","glasses":"none"}'),
('avatar_outfit_champion', 'Stadium Champion', 'A numbered team jersey, shoulder stripes, medal, trainers and matching sports cap. Matching accessories are included. Separately equipped accessories can be worn over this look.', 'avatar', null, 'common', 450, 'Shirt', '#e55d35', true, true, false, 651, '{"slot":"avatar_outfit","realmCollection":"general","top":"adventure_champion","bottom":"trackpants","shoeStyle":"sneakers","shirt":"#e7eef5","shirtTrim":"#e55d35","pants":"#1f3857","shoes":"#e55d35","hat":"cap","hatColor":"#1f3857","cape":"none","capeColor":"#1f3857","backpack":"none","backpackColor":"#1f3857","held":"none","glasses":"none"}'),
('avatar_outfit_guardian', 'Royal Guardian', 'Sculpted silver armour, blue shield crest, open-face helmet, royal cape and knight’s sword. Matching accessories are included. Separately equipped accessories can be worn over this look.', 'avatar', null, 'rare', 650, 'Shirt', '#dfb760', true, true, false, 652, '{"slot":"avatar_outfit","realmCollection":"general","top":"adventure_guardian","bottom":"joggers","shoeStyle":"boots","shirt":"#9bafc0","shirtTrim":"#dfb760","pants":"#263b5b","shoes":"#778b9f","hat":"knight","hatColor":"#9bafc0","cape":"royal","capeColor":"#284f87","backpack":"none","backpackColor":"#284f87","held":"knights_sword","glasses":"none"}'),
('avatar_outfit_mage', 'Moonlight Mage', 'A split midnight robe, crescent clasp, embroidered stars, pointed hat, cape and crystal wand. Matching accessories are included. Separately equipped accessories can be worn over this look.', 'avatar', null, 'rare', 750, 'Shirt', '#e5cd85', true, true, false, 653, '{"slot":"avatar_outfit","realmCollection":"general","top":"adventure_mage","bottom":"joggers","shoeStyle":"boots","shirt":"#223b5e","shirtTrim":"#e5cd85","pants":"#263047","shoes":"#374665","hat":"wizard","hatColor":"#223b5e","cape":"hero","capeColor":"#31547a","backpack":"none","backpackColor":"#31547a","held":"crystal_wand","glasses":"none"}'),
('avatar_outfit_astronaut', 'Orbital Astronaut', 'A panelled pressure suit, control console, clear bubble helmet, moon boots and rocket pack. Matching accessories are included. Separately equipped accessories can be worn over this look.', 'avatar', null, 'rare', 900, 'Shirt', '#ed813e', true, true, false, 654, '{"slot":"avatar_outfit","realmCollection":"general","top":"adventure_astronaut","bottom":"joggers","shoeStyle":"boots","shirt":"#e3eaf0","shirtTrim":"#ed813e","pants":"#b8c7d4","shoes":"#dbe5ee","hat":"astronaut","hatColor":"#e3eaf0","cape":"none","capeColor":"#e3eaf0","backpack":"rocket","backpackColor":"#dbe5ee","held":"none","glasses":"none"}')
on conflict (item_key) do nothing;
commit;
