-- Additive realm building XP catalogue. Existing inventories, balances and student RPC guards are unchanged.
begin;
insert into public.economy_items (item_key, name, description, category, realm_id, rarity, price, icon, accent, active, purchasable, discoverable, sort_order, metadata) values
('central_world_plot_1_nexus_tower', 'Number Nexus Apartments', 'A tall futuristic apartment block with illuminated balconies, teal circuitry and an orbital rooftop reactor. Unlock once, place multiple copies and choose your colours. Exterior only.', 'decoration', null, 'legendary', 2800, 'house', '#39adb2', true, true, true, 14, '{"slot":"world_plot_1","worldPlotId":"customisation-plot-1","worldAssetKey":"nexus_tower","worldArea":"buildings","marketplaceCategory":"buildings","worldCollection":"country","realmCollection":"number","realmName":"Number Nexus","gridSize":"6x6","tier":3,"marketplace_visual":{"type":"asset","src":"/marketplace/world-renders/nexus_tower.webp","alt":"Number Nexus Apartments — actual world model","previewMode":"world"}}'),
('central_world_plot_1_measure_lodge', 'Measurelands House', 'An ornate brass-and-gold home with violet arched windows, ruler details and pointed corner towers. Unlock once, place multiple copies and choose your colours. Exterior only.', 'decoration', null, 'rare', 700, 'house', '#c69a50', true, true, true, 15, '{"slot":"world_plot_1","worldPlotId":"customisation-plot-1","worldAssetKey":"measure_lodge","worldArea":"buildings","marketplaceCategory":"buildings","worldCollection":"country","realmCollection":"measurement","realmName":"Measurelands","gridSize":"5x5","tier":2,"marketplace_visual":{"type":"asset","src":"/marketplace/world-renders/measure_lodge.webp","alt":"Measurelands House — actual world model","previewMode":"world"}}'),
('central_world_plot_1_pattern_loom', 'Pattern Peaks Crystal House', 'An angular emerald-and-violet home with diamond roof terraces and crystal pillars. Unlock once, place multiple copies and choose your colours. Exterior only.', 'decoration', null, 'rare', 750, 'house', '#9672b8', true, true, true, 16, '{"slot":"world_plot_1","worldPlotId":"customisation-plot-1","worldAssetKey":"pattern_loom","worldArea":"buildings","marketplaceCategory":"buildings","worldCollection":"country","realmCollection":"pattern","realmName":"Pattern Peaks","gridSize":"5x5","tier":2,"marketplace_visual":{"type":"asset","src":"/marketplace/world-renders/pattern_loom.webp","alt":"Pattern Peaks Crystal House — actual world model","previewMode":"world"}}'),
('central_world_plot_1_stats_station', 'Statistica Glasshouse', 'A white-stone home with green glass conservatory domes, gold trim and a lookout turret. Unlock once, place multiple copies and choose your colours. Exterior only.', 'decoration', null, 'rare', 800, 'house', '#628ca0', true, true, true, 17, '{"slot":"world_plot_1","worldPlotId":"customisation-plot-1","worldAssetKey":"stats_station","worldArea":"buildings","marketplaceCategory":"buildings","worldCollection":"country","realmCollection":"statistics","realmName":"Statistica","gridSize":"5x5","tier":2,"marketplace_visual":{"type":"asset","src":"/marketplace/world-renders/stats_station.webp","alt":"Statistica Glasshouse — actual world model","previewMode":"world"}}'),
('central_world_plot_1_chance_games', 'Chance Hollow Fortune House', 'A mysterious rose-and-violet house with pointed towers, a glowing entrance and a fortune-wheel crest. Unlock once, place multiple copies and choose your colours. Exterior only.', 'decoration', null, 'rare', 650, 'house', '#b9825c', true, true, true, 18, '{"slot":"world_plot_1","worldPlotId":"customisation-plot-1","worldAssetKey":"chance_games","worldArea":"buildings","marketplaceCategory":"buildings","worldCollection":"country","realmCollection":"chance","realmName":"Chance Hollow","gridSize":"5x5","tier":2,"marketplace_visual":{"type":"asset","src":"/marketplace/world-renders/chance_games.webp","alt":"Chance Hollow Fortune House — actual world model","previewMode":"world"}}'),
('central_world_plot_1_star_habitat', 'Starpath Orbital Home', 'Connected violet habitat domes with cyan orbital bands, silver ribs and a solar canopy. Unlock once, place multiple copies and choose your colours. Exterior only.', 'decoration', null, 'rare', 950, 'house', '#7379b8', true, true, true, 19, '{"slot":"world_plot_1","worldPlotId":"customisation-plot-1","worldAssetKey":"star_habitat","worldArea":"buildings","marketplaceCategory":"buildings","worldCollection":"country","realmCollection":"space","realmName":"Starpath","gridSize":"5x5","tier":2,"marketplace_visual":{"type":"asset","src":"/marketplace/world-renders/star_habitat.webp","alt":"Starpath Orbital Home — actual world model","previewMode":"world"}}')
on conflict (item_key) do nothing;
commit;
